<a href="https://colab.research.google.com/github/iiiyahiya111/Project/blob/main/AgroClim_Combined_2010_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

from google.colab import drive
from pathlib import Path

# Mount Google Drive
drive.mount('/content/drive')

# Search locations in Google Drive
search_roots = [
    Path('/content/drive/MyDrive'),
    Path('/content/drive/Shareddrives')
]

matches = []

for root in search_roots:
    if root.exists():
        matches.extend(root.rglob('dataverse_files.zip'))

if not matches:
    raise FileNotFoundError(
        "dataverse_files.zip not found. "
        "Check its filename and location in Google Drive."
    )

print("ZIP file(s) found:")

for i, path in enumerate(matches, start=1):
    print(f"{i}. {path}")

# Select the first match
ZIP_PATH = matches[0]

print("\nSelected ZIP file:", ZIP_PATH)
print("File size:", round(ZIP_PATH.stat().st_size / (1024**2), 2), "MB")

Mounted at /content/drive
ZIP file(s) found:
1. /content/drive/MyDrive/dataverse_files.zip

Selected ZIP file: /content/drive/MyDrive/dataverse_files.zip
File size: 146.26 MB

In [2]:

import zipfile
from collections import Counter
from pathlib import PurePosixPath

with zipfile.ZipFile(ZIP_PATH, 'r') as zf:
    infos = [info for info in zf.infolist() if not info.is_dir()]

    print("Total files:", len(infos))
    print("\nFile extensions:")

    extension_counts = Counter(
        PurePosixPath(info.filename).suffix.lower() or "[no extension]"
        for info in infos
    )

    for ext, count in extension_counts.most_common():
        print(f"{ext}: {count} file(s)")

    print("\nFiles inside ZIP:")

    for info in infos[:200]:
        size_kb = info.file_size / 1024
        print(f"{info.filename}  |  {size_kb:.2f} KB")

    if len(infos) > 200:
        print(f"\n...and {len(infos) - 200} more files.")

Total files: 112

File extensions:
.csv: 110 file(s)
.md: 1 file(s)
.txt: 1 file(s)

Files inside ZIP:
variables_brutes_et_elaborees.csv  |  11.83 KB
README.md  |  3.42 KB
stations_inrae_en_service.csv  |  3.77 KB
Station_Agroclim_INRAE_13103002_daily_1992_2025.csv  |  1712.39 KB
Station_Agroclim_INRAE_34172005_hourly_1990_2025.csv  |  13746.70 KB
Station_Agroclim_INRAE_30258005_hourly_1986_2025.csv  |  13308.20 KB
Station_Agroclim_INRAE_34237001_daily_1992_2025.csv  |  1722.50 KB
Station_Agroclim_INRAE_24340001_daily_2021_2025.csv  |  269.90 KB
Station_Agroclim_INRAE_74281004_daily_2010_2025.csv  |  782.25 KB
Station_Agroclim_INRAE_30034004_daily_1995_2025.csv  |  1688.23 KB
Station_Agroclim_INRAE_33080002_daily_1993_2025.csv  |  1838.10 KB
Station_Agroclim_INRAE_97117001_daily_1988_2025.csv  |  1888.65 KB
Station_Agroclim_INRAE_21106002_daily_1990_2025.csv  |  1928.75 KB
Station_Agroclim_INRAE_30258005_daily_1986_2025.csv  |  1955.90 KB
Station_Agroclim_INRAE_68066002_daily_1985_2025.csv  |  1985.10 KB
Station_Agroclim_INRAE_51242002_daily_1985_2025.csv  |  2085.12 KB
Station_Agroclim_INRAE_20303002_daily_1985_2025.csv  |  2097.24 KB
Station_Agroclim_INRAE_33533002_hourly_2013_2025.csv  |  5768.74 KB
Station_Agroclim_INRAE_12232002_hourly_1988_2025.csv  |  12662.65 KB
Station_Agroclim_INRAE_80557001_hourly_1985_2025.csv  |  13389.79 KB
Station_Agroclim_INRAE_35240002_hourly_1983_2025.csv  |  13846.80 KB
Station_Agroclim_INRAE_91272001_daily_2019_2025.csv  |  353.59 KB
Station_Agroclim_INRAE_63113002_daily_2017_2025.csv  |  503.81 KB
Station_Agroclim_INRAE_39130003_daily_2014_2025.csv  |  672.52 KB
Station_Agroclim_INRAE_68028003_daily_1999_2025.csv  |  1501.11 KB
Station_Agroclim_INRAE_63189002_daily_1995_2025.csv  |  1588.19 KB
Station_Agroclim_INRAE_56144001_daily_1993_2025.csv  |  1800.87 KB
Station_Agroclim_INRAE_80557001_daily_1985_2025.csv  |  2050.44 KB
Station_Agroclim_INRAE_97117001_hourly_1988_2025.csv  |  11787.15 KB
Station_Agroclim_INRAE_11170004_hourly_1989_2025.csv  |  13412.11 KB
Station_Agroclim_INRAE_51242002_hourly_1985_2025.csv  |  13851.62 KB
Station_Agroclim_INRAE_34337004_daily_2013_2025.csv  |  737.71 KB
Station_Agroclim_INRAE_33533002_daily_2013_2025.csv  |  750.08 KB
Station_Agroclim_INRAE_34172005_daily_1990_2025.csv  |  1905.75 KB
Station_Agroclim_INRAE_66002002_daily_1991_2025.csv  |  1905.98 KB
Station_Agroclim_INRAE_47038002_daily_1991_2025.csv  |  1919.22 KB
Station_Agroclim_INRAE_84007004_daily_1988_2025.csv  |  2027.60 KB
Station_Agroclim_INRAE_17353002_hourly_1985_2025.csv  |  13215.98 KB
Station_Agroclim_INRAE_86139002_hourly_1988_2025.csv  |  13465.20 KB
Station_Agroclim_INRAE_44026001_daily_2013_2025.csv  |  750.62 KB
Station_Agroclim_INRAE_34154004_daily_2012_2025.csv  |  821.81 KB
Station_Agroclim_INRAE_34150002_daily_1999_2025.csv  |  1451.92 KB
Station_Agroclim_INRAE_31035002_daily_1994_2025.csv  |  1744.89 KB
Station_Agroclim_INRAE_78615002_daily_1992_2025.csv  |  1747.17 KB
Station_Agroclim_INRAE_49249001_daily_2012_2025.csv  |  810.28 KB
Station_Agroclim_INRAE_45234009_daily_2010_2025.csv  |  889.19 KB
Station_Agroclim_INRAE_61328003_daily_2010_2025.csv  |  927.63 KB
Station_Agroclim_INRAE_78646005_daily_2001_2025.csv  |  1343.92 KB
Station_Agroclim_INRAE_33122004_daily_1996_2025.csv  |  1585.04 KB
Station_Agroclim_INRAE_39130003_hourly_2014_2025.csv  |  5171.58 KB
Station_Agroclim_INRAE_74281004_hourly_2010_2025.csv  |  6483.91 KB
Station_Agroclim_INRAE_45234009_hourly_2010_2025.csv  |  6852.14 KB
Station_Agroclim_INRAE_78646005_hourly_2001_2025.csv  |  10946.46 KB
Station_Agroclim_INRAE_97118002_hourly_1993_2025.csv  |  12677.15 KB
Station_Agroclim_INRAE_47038002_hourly_1991_2025.csv  |  13989.08 KB
Station_Agroclim_INRAE_97015001_daily_1995_2025.csv  |  1474.87 KB
Station_Agroclim_INRAE_46084002_daily_1992_2025.csv  |  1828.36 KB
Station_Agroclim_INRAE_29170002_daily_1991_2025.csv  |  1877.59 KB
Station_Agroclim_INRAE_24340001_hourly_2021_2025.csv  |  2071.46 KB
Station_Agroclim_INRAE_35240002_daily_1983_2025.csv  |  2173.54 KB
Station_Agroclim_INRAE_63189002_hourly_1995_2025.csv  |  12865.69 KB
Station_Agroclim_INRAE_56144001_hourly_1993_2025.csv  |  13697.12 KB
Station_Agroclim_INRAE_97119001_daily_1994_2025.csv  |  1661.61 KB
Station_Agroclim_INRAE_29179002_daily_1993_2025.csv  |  1826.37 KB
Station_Agroclim_INRAE_63113002_hourly_2017_2025.csv  |  3944.66 KB
Station_Agroclim_INRAE_44026001_hourly_2013_2025.csv  |  5788.12 KB
Station_Agroclim_INRAE_31035002_hourly_1994_2025.csv  |  13290.28 KB
Station_Agroclim_INRAE_97118002_daily_1993_2025.csv  |  1753.83 KB
Station_Agroclim_INRAE_88304005_daily_1989_2025.csv  |  1932.22 KB
Station_Agroclim_INRAE_11170004_daily_1989_2025.csv  |  1945.92 KB
Station_Agroclim_INRAE_12232002_daily_1988_2025.csv  |  1948.30 KB
Station_Agroclim_INRAE_54113002_daily_1992_2025.csv  |  1816.55 KB
Station_Agroclim_INRAE_40272002_daily_1993_2025.csv  |  1839.46 KB
Station_Agroclim_INRAE_30117002_daily_1991_2025.csv  |  1900.67 KB
Station_Agroclim_INRAE_33550003_daily_1991_2025.csv  |  1902.87 KB
Station_Agroclim_INRAE_17353002_daily_1985_2025.csv  |  2119.58 KB
Station_Agroclim_INRAE_91272001_hourly_2019_2025.csv  |  2746.42 KB
Station_Agroclim_INRAE_34150002_hourly_1999_2025.csv  |  11207.34 KB
Station_Agroclim_INRAE_26313003_daily_1990_2025.csv  |  1926.52 KB
Station_Agroclim_INRAE_49215002_daily_1986_2025.csv  |  2083.48 KB
Station_Agroclim_INRAE_29179002_hourly_1993_2025.csv  |  13833.23 KB
Station_Agroclim_INRAE_63345002_daily_1985_2025.csv  |  2012.33 KB
Station_Agroclim_INRAE_86139002_daily_1988_2025.csv  |  2012.83 KB
Station_Agroclim_INRAE_34337004_hourly_2013_2025.csv  |  5705.42 KB
Station_Agroclim_INRAE_88304005_hourly_1989_2025.csv  |  11720.71 KB
Station_Agroclim_INRAE_97119001_hourly_1994_2025.csv  |  12685.42 KB
Station_Agroclim_INRAE_33122004_hourly_1996_2025.csv  |  12736.88 KB
Station_Agroclim_INRAE_21106002_hourly_1990_2025.csv  |  13865.12 KB
Station_Agroclim_INRAE_49249001_hourly_2012_2025.csv  |  6269.15 KB
Station_Agroclim_INRAE_34154004_hourly_2012_2025.csv  |  6357.73 KB
Station_Agroclim_INRAE_61328003_hourly_2010_2025.csv  |  7146.29 KB
Station_Agroclim_INRAE_68066002_hourly_1985_2025.csv  |  11202.55 KB
Station_Agroclim_INRAE_13103002_hourly_1992_2025.csv  |  13696.66 KB
Station_Agroclim_INRAE_30117002_hourly_1991_2025.csv  |  13908.90 KB
Station_Agroclim_INRAE_29170002_hourly_1991_2025.csv  |  13929.42 KB
Station_Agroclim_INRAE_68028003_hourly_1999_2025.csv  |  11526.19 KB
Station_Agroclim_INRAE_34237001_hourly_1992_2025.csv  |  13872.27 KB
Station_Agroclim_INRAE_97015001_hourly_1995_2025.csv  |  12442.12 KB
Station_Agroclim_INRAE_30034004_hourly_1995_2025.csv  |  12801.95 KB
Station_Agroclim_INRAE_78615002_hourly_1992_2025.csv  |  13667.78 KB
Station_Agroclim_INRAE_20303002_hourly_1985_2025.csv  |  13793.95 KB
Station_Agroclim_INRAE_63345002_hourly_1985_2025.csv  |  13688.12 KB
Station_Agroclim_INRAE_54113002_hourly_1992_2025.csv  |  13836.48 KB
Station_Agroclim_INRAE_40272002_hourly_1993_2025.csv  |  13941.25 KB
Station_Agroclim_INRAE_46084002_hourly_1992_2025.csv  |  13852.79 KB
Station_Agroclim_INRAE_26313003_hourly_1990_2025.csv  |  13930.22 KB
Station_Agroclim_INRAE_49215002_hourly_1986_2025.csv  |  13934.75 KB
Station_Agroclim_INRAE_66002002_hourly_1991_2025.csv  |  14025.94 KB
Station_Agroclim_INRAE_33080002_hourly_1993_2025.csv  |  13969.82 KB
Station_Agroclim_INRAE_84007004_hourly_1988_2025.csv  |  14011.04 KB
Station_Agroclim_INRAE_33550003_hourly_1991_2025.csv  |  14019.12 KB
MANIFEST.TXT  |  10.60 KB

In [3]:

from pathlib import Path
import zipfile

EXTRACT_DIR = Path('/content/dataset_inspection')
EXTRACT_DIR.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, 'r') as zf:
    # Basic path-safety check
    base = EXTRACT_DIR.resolve()

    for info in zf.infolist():
        destination = (EXTRACT_DIR / info.filename).resolve()

        if destination != base and base not in destination.parents:
            raise ValueError(
                f"Unsafe path inside ZIP: {info.filename}"
            )

    zf.extractall(EXTRACT_DIR)

print("Extraction complete.")
print("Dataset folder:", EXTRACT_DIR)

Extraction complete.
Dataset folder: /content/dataset_inspection

In [4]:

files = sorted(
    p for p in EXTRACT_DIR.rglob('*')
    if p.is_file()
)

print("Total extracted files:", len(files))
print("\nExtracted directory structure:\n")

for path in files[:250]:
    relative_path = path.relative_to(EXTRACT_DIR)
    size_kb = path.stat().st_size / 1024

    print(f"{relative_path}  |  {size_kb:.2f} KB")

if len(files) > 250:
    print(f"\n...and {len(files) - 250} more files.")

Total extracted files: 112

Extracted directory structure:

MANIFEST.TXT  |  10.60 KB
README.md  |  3.42 KB
Station_Agroclim_INRAE_11170004_daily_1989_2025.csv  |  1945.92 KB
Station_Agroclim_INRAE_11170004_hourly_1989_2025.csv  |  13412.11 KB
Station_Agroclim_INRAE_12232002_daily_1988_2025.csv  |  1948.30 KB
Station_Agroclim_INRAE_12232002_hourly_1988_2025.csv  |  12662.65 KB
Station_Agroclim_INRAE_13103002_daily_1992_2025.csv  |  1712.39 KB
Station_Agroclim_INRAE_13103002_hourly_1992_2025.csv  |  13696.66 KB
Station_Agroclim_INRAE_17353002_daily_1985_2025.csv  |  2119.58 KB
Station_Agroclim_INRAE_17353002_hourly_1985_2025.csv  |  13215.98 KB
Station_Agroclim_INRAE_20303002_daily_1985_2025.csv  |  2097.24 KB
Station_Agroclim_INRAE_20303002_hourly_1985_2025.csv  |  13793.95 KB
Station_Agroclim_INRAE_21106002_daily_1990_2025.csv  |  1928.75 KB
Station_Agroclim_INRAE_21106002_hourly_1990_2025.csv  |  13865.12 KB
Station_Agroclim_INRAE_24340001_daily_2021_2025.csv  |  269.90 KB
Station_Agroclim_INRAE_24340001_hourly_2021_2025.csv  |  2071.46 KB
Station_Agroclim_INRAE_26313003_daily_1990_2025.csv  |  1926.52 KB
Station_Agroclim_INRAE_26313003_hourly_1990_2025.csv  |  13930.22 KB
Station_Agroclim_INRAE_29170002_daily_1991_2025.csv  |  1877.59 KB
Station_Agroclim_INRAE_29170002_hourly_1991_2025.csv  |  13929.42 KB
Station_Agroclim_INRAE_29179002_daily_1993_2025.csv  |  1826.37 KB
Station_Agroclim_INRAE_29179002_hourly_1993_2025.csv  |  13833.23 KB
Station_Agroclim_INRAE_30034004_daily_1995_2025.csv  |  1688.23 KB
Station_Agroclim_INRAE_30034004_hourly_1995_2025.csv  |  12801.95 KB
Station_Agroclim_INRAE_30117002_daily_1991_2025.csv  |  1900.67 KB
Station_Agroclim_INRAE_30117002_hourly_1991_2025.csv  |  13908.90 KB
Station_Agroclim_INRAE_30258005_daily_1986_2025.csv  |  1955.90 KB
Station_Agroclim_INRAE_30258005_hourly_1986_2025.csv  |  13308.20 KB
Station_Agroclim_INRAE_31035002_daily_1994_2025.csv  |  1744.89 KB
Station_Agroclim_INRAE_31035002_hourly_1994_2025.csv  |  13290.28 KB
Station_Agroclim_INRAE_33080002_daily_1993_2025.csv  |  1838.10 KB
Station_Agroclim_INRAE_33080002_hourly_1993_2025.csv  |  13969.82 KB
Station_Agroclim_INRAE_33122004_daily_1996_2025.csv  |  1585.04 KB
Station_Agroclim_INRAE_33122004_hourly_1996_2025.csv  |  12736.88 KB
Station_Agroclim_INRAE_33533002_daily_2013_2025.csv  |  750.08 KB
Station_Agroclim_INRAE_33533002_hourly_2013_2025.csv  |  5768.74 KB
Station_Agroclim_INRAE_33550003_daily_1991_2025.csv  |  1902.87 KB
Station_Agroclim_INRAE_33550003_hourly_1991_2025.csv  |  14019.12 KB
Station_Agroclim_INRAE_34150002_daily_1999_2025.csv  |  1451.92 KB
Station_Agroclim_INRAE_34150002_hourly_1999_2025.csv  |  11207.34 KB
Station_Agroclim_INRAE_34154004_daily_2012_2025.csv  |  821.81 KB
Station_Agroclim_INRAE_34154004_hourly_2012_2025.csv  |  6357.73 KB
Station_Agroclim_INRAE_34172005_daily_1990_2025.csv  |  1905.75 KB
Station_Agroclim_INRAE_34172005_hourly_1990_2025.csv  |  13746.70 KB
Station_Agroclim_INRAE_34237001_daily_1992_2025.csv  |  1722.50 KB
Station_Agroclim_INRAE_34237001_hourly_1992_2025.csv  |  13872.27 KB
Station_Agroclim_INRAE_34337004_daily_2013_2025.csv  |  737.71 KB
Station_Agroclim_INRAE_34337004_hourly_2013_2025.csv  |  5705.42 KB
Station_Agroclim_INRAE_35240002_daily_1983_2025.csv  |  2173.54 KB
Station_Agroclim_INRAE_35240002_hourly_1983_2025.csv  |  13846.80 KB
Station_Agroclim_INRAE_39130003_daily_2014_2025.csv  |  672.52 KB
Station_Agroclim_INRAE_39130003_hourly_2014_2025.csv  |  5171.58 KB
Station_Agroclim_INRAE_40272002_daily_1993_2025.csv  |  1839.46 KB
Station_Agroclim_INRAE_40272002_hourly_1993_2025.csv  |  13941.25 KB
Station_Agroclim_INRAE_44026001_daily_2013_2025.csv  |  750.62 KB
Station_Agroclim_INRAE_44026001_hourly_2013_2025.csv  |  5788.12 KB
Station_Agroclim_INRAE_45234009_daily_2010_2025.csv  |  889.19 KB
Station_Agroclim_INRAE_45234009_hourly_2010_2025.csv  |  6852.14 KB
Station_Agroclim_INRAE_46084002_daily_1992_2025.csv  |  1828.36 KB
Station_Agroclim_INRAE_46084002_hourly_1992_2025.csv  |  13852.79 KB
Station_Agroclim_INRAE_47038002_daily_1991_2025.csv  |  1919.22 KB
Station_Agroclim_INRAE_47038002_hourly_1991_2025.csv  |  13989.08 KB
Station_Agroclim_INRAE_49215002_daily_1986_2025.csv  |  2083.48 KB
Station_Agroclim_INRAE_49215002_hourly_1986_2025.csv  |  13934.75 KB
Station_Agroclim_INRAE_49249001_daily_2012_2025.csv  |  810.28 KB
Station_Agroclim_INRAE_49249001_hourly_2012_2025.csv  |  6269.15 KB
Station_Agroclim_INRAE_51242002_daily_1985_2025.csv  |  2085.12 KB
Station_Agroclim_INRAE_51242002_hourly_1985_2025.csv  |  13851.62 KB
Station_Agroclim_INRAE_54113002_daily_1992_2025.csv  |  1816.55 KB
Station_Agroclim_INRAE_54113002_hourly_1992_2025.csv  |  13836.48 KB
Station_Agroclim_INRAE_56144001_daily_1993_2025.csv  |  1800.87 KB
Station_Agroclim_INRAE_56144001_hourly_1993_2025.csv  |  13697.12 KB
Station_Agroclim_INRAE_61328003_daily_2010_2025.csv  |  927.63 KB
Station_Agroclim_INRAE_61328003_hourly_2010_2025.csv  |  7146.29 KB
Station_Agroclim_INRAE_63113002_daily_2017_2025.csv  |  503.81 KB
Station_Agroclim_INRAE_63113002_hourly_2017_2025.csv  |  3944.66 KB
Station_Agroclim_INRAE_63189002_daily_1995_2025.csv  |  1588.19 KB
Station_Agroclim_INRAE_63189002_hourly_1995_2025.csv  |  12865.69 KB
Station_Agroclim_INRAE_63345002_daily_1985_2025.csv  |  2012.33 KB
Station_Agroclim_INRAE_63345002_hourly_1985_2025.csv  |  13688.12 KB
Station_Agroclim_INRAE_66002002_daily_1991_2025.csv  |  1905.98 KB
Station_Agroclim_INRAE_66002002_hourly_1991_2025.csv  |  14025.94 KB
Station_Agroclim_INRAE_68028003_daily_1999_2025.csv  |  1501.11 KB
Station_Agroclim_INRAE_68028003_hourly_1999_2025.csv  |  11526.19 KB
Station_Agroclim_INRAE_68066002_daily_1985_2025.csv  |  1985.10 KB
Station_Agroclim_INRAE_68066002_hourly_1985_2025.csv  |  11202.55 KB
Station_Agroclim_INRAE_74281004_daily_2010_2025.csv  |  782.25 KB
Station_Agroclim_INRAE_74281004_hourly_2010_2025.csv  |  6483.91 KB
Station_Agroclim_INRAE_78615002_daily_1992_2025.csv  |  1747.17 KB
Station_Agroclim_INRAE_78615002_hourly_1992_2025.csv  |  13667.78 KB
Station_Agroclim_INRAE_78646005_daily_2001_2025.csv  |  1343.92 KB
Station_Agroclim_INRAE_78646005_hourly_2001_2025.csv  |  10946.46 KB
Station_Agroclim_INRAE_80557001_daily_1985_2025.csv  |  2050.44 KB
Station_Agroclim_INRAE_80557001_hourly_1985_2025.csv  |  13389.79 KB
Station_Agroclim_INRAE_84007004_daily_1988_2025.csv  |  2027.60 KB
Station_Agroclim_INRAE_84007004_hourly_1988_2025.csv  |  14011.04 KB
Station_Agroclim_INRAE_86139002_daily_1988_2025.csv  |  2012.83 KB
Station_Agroclim_INRAE_86139002_hourly_1988_2025.csv  |  13465.20 KB
Station_Agroclim_INRAE_88304005_daily_1989_2025.csv  |  1932.22 KB
Station_Agroclim_INRAE_88304005_hourly_1989_2025.csv  |  11720.71 KB
Station_Agroclim_INRAE_91272001_daily_2019_2025.csv  |  353.59 KB
Station_Agroclim_INRAE_91272001_hourly_2019_2025.csv  |  2746.42 KB
Station_Agroclim_INRAE_97015001_daily_1995_2025.csv  |  1474.87 KB
Station_Agroclim_INRAE_97015001_hourly_1995_2025.csv  |  12442.12 KB
Station_Agroclim_INRAE_97117001_daily_1988_2025.csv  |  1888.65 KB
Station_Agroclim_INRAE_97117001_hourly_1988_2025.csv  |  11787.15 KB
Station_Agroclim_INRAE_97118002_daily_1993_2025.csv  |  1753.83 KB
Station_Agroclim_INRAE_97118002_hourly_1993_2025.csv  |  12677.15 KB
Station_Agroclim_INRAE_97119001_daily_1994_2025.csv  |  1661.61 KB
Station_Agroclim_INRAE_97119001_hourly_1994_2025.csv  |  12685.42 KB
stations_inrae_en_service.csv  |  3.77 KB
variables_brutes_et_elaborees.csv  |  11.83 KB

In [5]:

from pathlib import Path
import pandas as pd
import csv
import re

BASE_DIR = Path('/content/dataset_inspection')

if not BASE_DIR.exists():
    raise FileNotFoundError(
        "Dataset folder not found. Run the previous extraction cell first."
    )

# 1. Read dataset documentation
for filename in ['README.md', 'MANIFEST.TXT']:
    path = BASE_DIR / filename

    if path.exists():
        print('\n' + '=' * 80)
        print(f'DOCUMENTATION: {filename}')
        print('=' * 80)
        print(path.read_text(encoding='utf-8', errors='replace')[:12000])


# 2. Helper to read a small CSV preview
def read_preview(path, nrows=8):
    with open(path, 'r', encoding='utf-8-sig', errors='replace') as f:
        sample = f.read(12000)

    try:
        delimiter = csv.Sniffer().sniff(
            sample, delimiters=';,\t|'
        ).delimiter
    except csv.Error:
        delimiter = ';'

    df = pd.read_csv(
        path,
        sep=delimiter,
        nrows=nrows,
        dtype=str,
        encoding='utf-8-sig',
        encoding_errors='replace',
        on_bad_lines='skip'
    )

    # Fallback if the delimiter was detected incorrectly
    if len(df.columns) <= 1:
        candidates = []

        for sep in [';', ',', '\t', '|']:
            try:
                test_df = pd.read_csv(
                    path,
                    sep=sep,
                    nrows=nrows,
                    dtype=str,
                    encoding='utf-8-sig',
                    encoding_errors='replace',
                    on_bad_lines='skip'
                )
                candidates.append((len(test_df.columns), sep, test_df))
            except Exception:
                pass

        if candidates:
            _, delimiter, df = max(candidates, key=lambda x: x[0])

    return df, delimiter


# 3. Inspect variable dictionary
variables_path = BASE_DIR / 'variables_brutes_et_elaborees.csv'

if variables_path.exists():
    variables_df, sep = read_preview(variables_path, nrows=500)

    print('\n' + '=' * 80)
    print('VARIABLE DICTIONARY')
    print('Detected delimiter:', repr(sep))
    print('Shape:', variables_df.shape)
    print('Columns:', variables_df.columns.tolist())
    print(variables_df.to_string(index=False, max_cols=20))

    # Look for relevant variables in every column
    pattern = (
        r'temp|humid|humect|leaf|wet|feuille|mouill|'
        r'LWD|dew.?point|point.?de.?rosée|HR|'
        r'pluie|rain|DPV|DPD'
    )

    text_rows = variables_df.fillna('').astype(str).agg(' '.join, axis=1)
    relevant = variables_df[
        text_rows.str.contains(pattern, case=False, regex=True)
    ]

    print('\nPOSSIBLY RELEVANT VARIABLES:')
    print(relevant.to_string(index=False, max_cols=20))


# 4. Inspect station metadata
stations_path = BASE_DIR / 'stations_inrae_en_service.csv'

if stations_path.exists():
    stations_df, sep = read_preview(stations_path, nrows=15)

    print('\n' + '=' * 80)
    print('STATION METADATA')
    print('Columns:', stations_df.columns.tolist())
    print(stations_df.head(15).to_string(index=False, max_cols=20))


# 5. Inspect one hourly station file
hourly_path = (
    BASE_DIR /
    'Station_Agroclim_INRAE_34172005_hourly_1990_2025.csv'
)

if hourly_path.exists():
    hourly_df, sep = read_preview(hourly_path, nrows=5)

    print('\n' + '=' * 80)
    print('HOURLY SAMPLE')
    print('File:', hourly_path.name)
    print('Detected delimiter:', repr(sep))
    print('Shape of preview:', hourly_df.shape)
    print('\nColumn names:')
    for col in hourly_df.columns:
        print(repr(col))

    print('\nFirst 5 rows:')
    print(hourly_df.head().to_string(index=False, max_cols=60))

else:
    print('\nSelected hourly file not found.')

================================================================================
DOCUMENTATION: README.md
================================================================================
Ce fichier README a été généré le [2025-05-04] par [Carina Furusho-Percot].
Dernière mise-à-jour le : [2026-08-04].

# INFORMATIONS GÉNÉRALES

## Titre du jeu de données :

Daily and hourly climatic data from 54 stations of the INRAE Agroclim network

## DOI :

<https://doi.org/10.57745/BQ0BWB>

Le data paper avec les informations a été publié dans Data-in-Brief :

> Furusho-Percot C., Maury O., Minet V., De Decker T., Roux D., Beauvois C., Le Roux R., Décome J., Launay M., and García de Cortázar-Atauri I. French agroclimatic research network dataset. In: Data in Brief, Volume 61, August 2025. DOI: [10.1016/j.dib.2025.111809](https://doi.org/10.1016/j.dib.2025.111809)

## Adresse de contact :

agroclim-contact@inrae.fr

# INFORMATIONS MÉTHODOLOGIQUES (FR/EN)

## Description des sources et méthodes utilisées pour collecter et générer les données :

FR
Les données climatiques horaires et journalières sont collectées à partir de 54 stations en France, y compris en Corse, en Guadeloupe et en Guyane (<https://agroclim.inrae.fr/carto/>). Chaque station est composée de 12 capteurs et mesure la température de l'air sous abri, l'humidité de l'air sous abri, la vitesse et la direction du vent, les précipitations, le rayonnement solaire global, le rayonnement photosynthétiquement actif, la durée d'humectation des feuilles, la température de l'air à 10 et 50 cm, et la température du sol à 10 et 50 cm de profondeur. Les données sont filtrées pour éliminer les principales valeurs aberrantes, avec des seuils dépendant de la saison.

EN
Measured daily and hourly climatic data from 54 currently active stations of the INRAE Agroclim network in France, Guyana and Guadeloupe. Each station is composed by 12 sensors and measures air temperature under shelter, air humidity under shelter, wind speed and direction, precipitation, global solar radiation, photosynthetically active radiation, leaf wetness duration, air temperature at 10 and 50 cm, and soil temperature at 10 and 50 cm depths. The daily data is filtered to remove main outliers, with season-dependent thresholds. Hourly data is raw and not yet filtered or validated.

## Méthodes de traitement des données :

Les méthodes de filtrage ont été appliquées aux données journalières des variables principales et suivent les méthodes décrites dans l'article : « RESISTANT, ROBUST AND NON-PARAMETRIC TECHNIQUES FOR THE ANALYSIS OF CLIMATE DATA: THEORY AND EXAMPLES, INCLUDING APPLICATIONS TO HISTORICAL RADIOSONDE STATION DATA » (https://www.gfdl.noaa.gov/bibliography/related_files/jrl9602.pdf)

Les codes en Python pour appliquer les filtres utilisés sont disponibles : <https://forge.inrae.fr/agroclim/reseauagrometeo/climatikqc>.

# APERÇUS DES DONNÉES ET FICHIERS

## Convention de nommage des fichiers :

Les données sont séparées par station et par pas de temps.

Les fichiers sont nommées par le code de la station INRAE (<https://agroclim.inrae.fr/carto/>), le pas de temps et la période couverte selon ce motif : `Station_Agroclim_INRAE_{numéro de station}_{pas de temps}_{première année}_{dernière année}.csv`.

La liste des stations est disponible dans `stations_inrae_en_service.csv`.

# INFORMATIONS SPÉCIFIQUES AUX DONNÉES :

## Liste des variables/entêtes de colonne :

Voir le fichier `variables_brutes_et_elaborees.csv` issu de <https://agroclim.inrae.fr/carto/downloadData?name=variables>.

## Code des valeurs manquantes :

Vide


================================================================================
DOCUMENTATION: MANIFEST.TXT
================================================================================
variables_brutes_et_elaborees.csv (text/comma-separated-values) 12114 bytes.
README.md (text/markdown) 3500 bytes.
stations_inrae_en_service.csv (text/comma-separated-values) 3861 bytes.
Station_Agroclim_INRAE_13103002_daily_1992_2025.csv (text/comma-separated-values) 1753490 bytes.
Station_Agroclim_INRAE_34172005_hourly_1990_2025.csv (text/comma-separated-values) 14076618 bytes.
Station_Agroclim_INRAE_30258005_hourly_1986_2025.csv (text/comma-separated-values) 13627592 bytes.
Station_Agroclim_INRAE_34237001_daily_1992_2025.csv (text/comma-separated-values) 1763836 bytes.
Station_Agroclim_INRAE_24340001_daily_2021_2025.csv (text/comma-separated-values) 276374 bytes.
Station_Agroclim_INRAE_74281004_daily_2010_2025.csv (text/comma-separated-values) 801027 bytes.
Station_Agroclim_INRAE_30034004_daily_1995_2025.csv (text/comma-separated-values) 1728750 bytes.
Station_Agroclim_INRAE_33080002_daily_1993_2025.csv (text/comma-separated-values) 1882213 bytes.
Station_Agroclim_INRAE_97117001_daily_1988_2025.csv (text/comma-separated-values) 1933982 bytes.
Station_Agroclim_INRAE_21106002_daily_1990_2025.csv (text/comma-separated-values) 1975039 bytes.
Station_Agroclim_INRAE_30258005_daily_1986_2025.csv (text/comma-separated-values) 2002840 bytes.
Station_Agroclim_INRAE_68066002_daily_1985_2025.csv (text/comma-separated-values) 2032738 bytes.
Station_Agroclim_INRAE_51242002_daily_1985_2025.csv (text/comma-separated-values) 2135159 bytes.
Station_Agroclim_INRAE_20303002_daily_1985_2025.csv (text/comma-separated-values) 2147572 bytes.
Station_Agroclim_INRAE_33533002_hourly_2013_2025.csv (text/comma-separated-values) 5907186 bytes.
Station_Agroclim_INRAE_12232002_hourly_1988_2025.csv (text/comma-separated-values) 12966556 bytes.
Station_Agroclim_INRAE_80557001_hourly_1985_2025.csv (text/comma-separated-values) 13711149 bytes.
Station_Agroclim_INRAE_35240002_hourly_1983_2025.csv (text/comma-separated-values) 14179124 bytes.
Station_Agroclim_INRAE_91272001_daily_2019_2025.csv (text/comma-separated-values) 362074 bytes.
Station_Agroclim_INRAE_63113002_daily_2017_2025.csv (text/comma-separated-values) 515903 bytes.
Station_Agroclim_INRAE_39130003_daily_2014_2025.csv (text/comma-separated-values) 688660 bytes.
Station_Agroclim_INRAE_68028003_daily_1999_2025.csv (text/comma-separated-values) 1537138 bytes.
Station_Agroclim_INRAE_63189002_daily_1995_2025.csv (text/comma-separated-values) 1626310 bytes.
Station_Agroclim_INRAE_56144001_daily_1993_2025.csv (text/comma-separated-values) 1844094 bytes.
Station_Agroclim_INRAE_80557001_daily_1985_2025.csv (text/comma-separated-values) 2099647 bytes.
Station_Agroclim_INRAE_97117001_hourly_1988_2025.csv (text/comma-separated-values) 12070042 bytes.
Station_Agroclim_INRAE_11170004_hourly_1989_2025.csv (text/comma-separated-values) 13734004 bytes.
Station_Agroclim_INRAE_51242002_hourly_1985_2025.csv (text/comma-separated-values) 14184054 bytes.
Station_Agroclim_INRAE_34337004_daily_2013_2025.csv (text/comma-separated-values) 755411 bytes.
Station_Agroclim_INRAE_33533002_daily_2013_2025.csv (text/comma-separated-values) 768086 bytes.
Station_Agroclim_INRAE_34172005_daily_1990_2025.csv (text/comma-separated-values) 1951484 bytes.
Station_Agroclim_INRAE_66002002_daily_1991_2025.csv (text/comma-separated-values) 1951725 bytes.
Station_Agroclim_INRAE_47038002_daily_1991_2025.csv (text/comma-separated-values) 1965278 bytes.
Station_Agroclim_INRAE_84007004_daily_1988_2025.csv (text/comma-separated-values) 2076261 bytes.
Station_Agroclim_INRAE_17353002_hourly_1985_2025.csv (text/comma-separated-values) 13533159 bytes.
Station_Agroclim_INRAE_86139002_hourly_1988_2025.csv (text/comma-separated-values) 13788364 bytes.
Station_Agroclim_INRAE_44026001_daily_2013_2025.csv (text/comma-separated-values) 768636 bytes.
Station_Agroclim_INRAE_34154004_daily_2012_2025.csv (text/comma-separated-values) 841537 bytes.
Station_Agroclim_INRAE_34150002_daily_1999_2025.csv (text/comma-separated-values) 1486771 bytes.
Station_Agroclim_INRAE_31035002_daily_1994_2025.csv (text/comma-separated-values) 1786769 bytes.
Station_Agroclim_INRAE_78615002_daily_1992_2025.csv (text/comma-separated-values) 1789107 bytes.
Station_Agroclim_INRAE_49249001_daily_2012_2025.csv (text/comma-separated-values) 829722 bytes.
Station_Agroclim_INRAE_45234009_daily_2010_2025.csv (text/comma-separated-values) 910526 bytes.
Station_Agroclim_INRAE_61328003_daily_2010_2025.csv (text/comma-separated-values) 949892 bytes.
Station_Agroclim_INRAE_78646005_daily_2001_2025.csv (text/comma-separated-values) 1376174 bytes.
Station_Agroclim_INRAE_33122004_daily_1996_2025.csv (text/comma-separated-values) 1623086 bytes.
Station_Agroclim_INRAE_39130003_hourly_2014_2025.csv (text/comma-separated-values) 5295702 bytes.
Station_Agroclim_INRAE_74281004_hourly_2010_2025.csv (text/comma-separated-values) 6639527 bytes.
Station_Agroclim_INRAE_45234009_hourly_2010_2025.csv (text/comma-separated-values) 7016588 bytes.
Station_Agroclim_INRAE_78646005_hourly_2001_2025.csv (text/comma-separated-values) 11209179 bytes.
Station_Agroclim_INRAE_97118002_hourly_1993_2025.csv (text/comma-separated-values) 12981405 bytes.
Station_Agroclim_INRAE_47038002_hourly_1991_2025.csv (text/comma-separated-values) 14324817 bytes.
Station_Agroclim_INRAE_97015001_daily_1995_2025.csv (text/comma-separated-values) 1510265 bytes.
Station_Agroclim_INRAE_46084002_daily_1992_2025.csv (text/comma-separated-values) 1872237 bytes.
Station_Agroclim_INRAE_29170002_daily_1991_2025.csv (text/comma-separated-values) 1922656 bytes.
Station_Agroclim_INRAE_24340001_hourly_2021_2025.csv (text/comma-separated-values) 2121172 bytes.
Station_Agroclim_INRAE_35240002_daily_1983_2025.csv (text/comma-separated-values) 2225709 bytes.
Station_Agroclim_INRAE_63189002_hourly_1995_2025.csv (text/comma-separated-values) 13174464 bytes.
Station_Agroclim_INRAE_56144001_hourly_1993_2025.csv (text/comma-separated-values) 14025855 bytes.
Station_Agroclim_INRAE_97119001_daily_1994_2025.csv (text/comma-separated-values) 1701485 bytes.
Station_Agroclim_INRAE_29179002_daily_1993_2025.csv (text/comma-separated-values) 1870204 bytes.
Station_Agroclim_INRAE_63113002_hourly_2017_2025.csv (text/comma-separated-values) 4039334 bytes.
Station_Agroclim_INRAE_44026001_hourly_2013_2025.csv (text/comma-separated-values) 5927034 bytes.
Station_Agroclim_INRAE_31035002_hourly_1994_2025.csv (text/comma-separated-values) 13609245 bytes.
Station_Agroclim_INRAE_97118002_daily_1993_2025.csv (text/comma-separated-values) 1795924 bytes.
Station_Agroclim_INRAE_88304005_daily_1989_2025.csv (text/comma-separated-values) 1978594 bytes.
Station_Agroclim_INRAE_11170004_daily_1989_2025.csv (text/comma-separated-values) 1992624 bytes.
Station_Agroclim_INRAE_12232002_daily_1988_2025.csv (text/comma-separated-values) 1995055 bytes.
Station_Agroclim_INRAE_54113002_daily_1992_2025.csv (text/comma-separated-values) 1860148 bytes.
Station_Agroclim_INRAE_40272002_daily_1993_2025.csv (text/comma-separated-values) 1883609 bytes.
Station_Agroclim_INRAE_30117002_daily_1991_2025.csv (text/comma-separated-values) 1946288 bytes.
Station_Agroclim_INRAE_33550003_daily_1991_2025.csv (text/comma-separated-values) 1948540 bytes.
Station_Agroclim_INRAE_17353002_daily_1985_2025.csv (text/comma-separated-values) 2170447 bytes.
Station_Agroclim_INRAE_91272001_hourly_2019_2025.csv (text/comma-separated-values) 2812339 bytes.
Station_Agroclim_INRAE_34150002_hourly_1999_2025.csv (text/comma-separated-values) 11476318 bytes.
Station_Agroclim_INRAE_26313003_daily_1990_2025.csv (text/comma-separated-values) 1972752 bytes.
Station_Agroclim_INRAE_49215002_daily_1986_2025.csv (text/comma-separated-values) 2133488 bytes.
Station_Agroclim_INRAE_29179002_hourly_1993_2025.csv (text/comma-separated-values) 14165224 bytes.
Station_Agroclim_INRAE_63345002_daily_1985_2025.csv (text/comma-separated-values) 2060625 bytes.
Station_Agroclim_INRAE_86139002_daily_1988_2025.csv (text/comma-separated-values) 2061135 bytes.
Station_Agroclim_INRAE_34337004_hourly_2013_2025.csv (text/comma-separated-values) 5842354 bytes.
Station_Agroclim_INRAE_88304005_hourly_1989_2025.csv (text/comma-separated-values) 12002007 bytes.
Station_Agroclim_INRAE_97119001_hourly_1994_2025.csv (text/comma-separated-values) 12989871 bytes.
Station_Agroclim_INRAE_33122004_hourly_1996_2025.csv (text/comma-separated-values) 13042565 bytes.
Station_Agroclim_INRAE_21106002_hourly_1990_2025.csv (text/comma-separated-values) 14197888 bytes.
Station_Agroclim_INRAE_49249001_hourly_2012_2025.csv (text/comma-separated-values) 6419606 bytes.
Station_Agroclim_INRAE_34154004_hourly_2012_2025.csv (text/comma-separated-values) 6510317 bytes.
Station_Agroclim_INRAE_61328003_hourly_2010_2025.csv (text/comma-separated-values) 7317796 bytes.
Station_Agroclim_INRAE_68066002_hourly_1985_2025.csv (text/comma-separated-values) 11471415 bytes.
Station_Agroclim_INRAE_13103002_hourly_1992_2025.csv (text/comma-separated-values) 14025382 bytes.
Station_Agroclim_INRAE_30117002_hourly_1991_2025.csv (text/comma-separated-values) 14242715 bytes.
Station_Agroclim_INRAE_29170002_hourly_1991_2025.csv (text/comma-separated-values) 14263721 bytes.
Station_Agroclim_INRAE_68028003_hourly_1999_2025.csv (text/comma-separated-values) 11802814 bytes.
Station_Agroclim_INRAE_34237001_hourly_1992_2025.csv (text/comma-separated-values) 14205205 bytes.
Station_Agroclim_INRAE_97015001_hourly_1995_2025.csv (text/comma-separated-values) 12740734 bytes.
Station_Agroclim_INRAE_30034004_hourly_1995_2025.csv (text/comma-separated-values) 13109197 bytes.
Station_Agroclim_INRAE_78615002_hourly_1992_2025.csv (text/comma-separated-values) 13995809 bytes.
Station_Agroclim_INRAE_20303002_hourly_1985_2025.csv (text/comma-separated-values) 14125001 bytes.
Station_Agroclim_INRAE_63345002_hourly_1985_2025.csv (text/comma-separated-values) 14016631 bytes.
Station_Agroclim_INRAE_54113002_hourly_1992_2025.csv (text/comma-separated-values) 14168555 bytes.
Station_Agroclim_INRAE_40272002_hourly_1993_2025.csv (text/comma-separated-values) 14275836 bytes.
Station_Agroclim_INRAE_46084002_hourly_1992_2025.csv (text/comma-separated-values) 14185253 bytes.
Station_Agroclim_INRAE_26313003_hourly_1990_2025.csv (text/comma-separated-values) 14264543 bytes.
Station_Agroclim_INRAE_49215002_hourly_1986_2025.csv (text/comma-separated-values) 14269182 bytes.
Station_Agroclim_INRAE_66002002_hourly_1991_2025.csv (text/comma-separated-values) 14362567 bytes.
Station_Agroclim_INRAE_33080002_hourly_1993_2025.csv (text/comma-separated-values) 14305092 bytes.
Station_Agroclim_INRAE_84007004_hourly_1988_2025.csv (text/comma-separated-values) 14347310 bytes.
Station_Agroclim_INRAE_33550003_hourly_1991_2025.csv (text/comma-separated-values) 14355584 bytes.


================================================================================
VARIABLE DICTIONARY
Detected delimiter: ','
Shape: (51, 7)
Columns: ['Variable', 'Name (French)', 'Name (English)', 'Time-step', 'Unit', 'Description (French)', 'Description (English)']
Variable                                         Name (French)                                     Name (English) Time-step               Unit                                                                                                                                                                           Description (French)                                                                                                                                             Description (English)
       H                             DUREE HUMECTATION HORAIRE                           HOURLY HUMIDITY DURATION    hourly  HEURE ET DIXIEMES                                                                                                        Durée d'humectation cumulée sur l'heure précédente, mesurée par un capteur de mouillage                                                                                                                Cumulative wetness duration over the previous hour
      I5                        INDICE ACTINOTHERMIQUE A 50 CM                       ACTINOTHERMAL INDEX AT 50 CM    hourly  HEURE ET DIXIEMES                                                                                                                                              Température à 50 cm au dessus du sol a été mesuré                                                                                                              Temperature at 50 cm above ground level was measured
   PAR_H                                       RAYONNEMENT PAR                                      PAR RADIATION    hourly         JOULES/CM2                                                                                                                                                                                Rayonnement PAR                                                                                                                                                     PAR radiation
      RG                            RAYONNEMENT GLOBAL HORAIRE                            HOURLY GLOBAL RADIATION    hourly         JOULES/CM2                                                                                                           Rayonnement global horaire mesuré avec un pyranomètre (cumul sur l'heure précédente)                                                                           Hourly global radiation measured with a pyranometer (cumulative over the previous hour)
      RR                            HAUTEUR DES PRECIPITATIONS                                    RAINFALL HEIGHT    hourly        MILLIMETRES                                                                                                            Précipitations horaires mesurées avec un pluviomètre (cumul sur l'heure précédente)                                                                               Hourly precipitation measured with a rain gauge (cumulative over the previous hour)
       T                      TEMPERATURE  INSTANTANEE HORAIRE                   HOURLY INSTANTANEOUS TEMPERATURE    hourly     DEGRES CELSIUS                                                                                                                                      Température instantanée mesurée sous abri à l'heure ronde                                                                                                  Instantaneous temperature measured under cover at the round hour
       U                         HUMIDITE INSTANTANEE  HORAIRE                      HOURLY INSTANTANEOUS HUMIDITY    hourly        POURCENTAGE                                                                                                                                         Humidité instantanée mesurée sous abri à l'heure ronde                                                                                                     Instantaneous humidity measured under cover at the round hour
      U8 TEMPS PENDANT LEQUEL :  80%<HUMIDITE< 90% SUR L'HEURE TIME DURING WHICH: 80%<HUMIDITY< 90% OVER THE HOUR    hourly HEURES ET DIXIEMES                                                                                                                           Durée journalière pendant laquelle l'humidité a été supérieure à 80%                                                                                                         Daily duration during which humidity was greater than 80%
      U9      TEMPS PENDANT LEQUEL : HUMIDITE >90% SUR L'HEURE     TIME DURING WHICH: HUMIDITY >90% OVER THE HOUR    hourly HEURES ET DIXIEMES                                                                                                                               Durée horaire pendant laquelle l'humidité a été supérieure à 90%                                                                                                        Hourly duration during which humidity was greater than 90%

In [6]:

import pandas as pd
import numpy as np
from pathlib import Path

file_path = (
    Path('/content/dataset_inspection') /
    'Station_Agroclim_INRAE_34172005_hourly_1990_2025.csv'
)

df = pd.read_csv(file_path, low_memory=False)

print("Dataset shape:", df.shape)
print("\nColumns:", df.columns.tolist())

# Convert relevant columns to numeric
for col in ['heure', 'h', 't', 'u', 'rr']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

df['date_j'] = pd.to_datetime(df['date_j'], errors='coerce')

# 1. Date and time coverage
print("\n--- TIME COVERAGE ---")
print("First date:", df['date_j'].min())
print("Last date:", df['date_j'].max())
print("Hour values:", sorted(df['heure'].dropna().unique()))

# 2. Missing data
print("\n--- MISSING VALUES ---")
missing = pd.DataFrame({
    'missing_count': df.isna().sum(),
    'missing_percent': (df.isna().mean() * 100).round(2)
})
print(missing.loc[['date_j', 'heure', 'h', 't', 'u', 'rr']])

# 3. Numeric ranges and distributions
print("\n--- VARIABLE STATISTICS ---")
for col in ['h', 't', 'u', 'rr']:
    if col in df.columns:
        print(f"\n{col}:")
        print(df[col].describe(
            percentiles=[0.01, 0.25, 0.50, 0.75, 0.99]
        ))

# 4. Basic quality checks
print("\n--- QUALITY FLAGS ---")

print("Duplicate date/hour records:",
      df.duplicated(subset=['date_j', 'heure']).sum())

print("RH below 0:",
      (df['u'] < 0).sum())

print("RH above 100:",
      (df['u'] > 100).sum())

# Wetness duration is expected to represent time within one hour.
print("h below 0:",
      (df['h'] < 0).sum())

print("h above 1 hour:",
      (df['h'] > 1).sum())

print("Complete rows for h, t and u:",
      df[['h', 't', 'u']].notna().all(axis=1).sum())

# 5. Show suspicious and usable records
print("\n--- SAMPLE RECORDS ---")
display(df[['station_id', 'date_j', 'heure', 't', 'u', 'h', 'rr']].head(10))

print("\n--- RECORDS WITH RH > 100 ---")
display(df.loc[df['u'] > 100, ['date_j', 'heure', 't', 'u', 'h']].head(10))

Dataset shape: (289272, 14)

Columns: ['station_id', 'date_j', 'heure', 'h', 'i5', 'par_h', 'rg', 'rr', 't', 'u', 'u8', 'u9', 'vt', 'vx']

--- TIME COVERAGE ---
First date: 1993-01-01 00:00:00
Last date: 2025-12-31 00:00:00
Hour values: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24)]

--- MISSING VALUES ---
        missing_count  missing_percent
date_j              0             0.00
heure               0             0.00
h              120164            41.54
t                 291             0.10
u                 285             0.10
rr               1401             0.48

--- VARIABLE STATISTICS ---

h:
count    169108.000000
mean          0.252404
std           0.417571
min           0.000000
1%            0.000000
25%           0.000000
50%           0.000000
75%           0.500000
99%           1.000000
max           1.000000
Name: h, dtype: float64

t:
count    288981.000000
mean         14.778845
std           8.039889
min         -13.300000
1%           -2.600000
25%           9.200000
50%          14.500000
75%          20.300000
99%          32.400000
max          43.800000
Name: t, dtype: float64

u:
count    288987.000000
mean         71.651645
std          22.248758
min           0.000000
1%           24.000000
25%          54.000000
50%          75.000000
75%          92.000000
99%         100.000000
max         107.000000
Name: u, dtype: float64

rr:
count    287871.000000
mean          0.085812
std           0.877036
min           0.000000
1%            0.000000
25%           0.000000
50%           0.000000
75%           0.000000
99%           2.000000
max          74.500000
Name: rr, dtype: float64

--- QUALITY FLAGS ---
Duplicate date/hour records: 0
RH below 0: 0
RH above 100: 874
h below 0: 0
h above 1 hour: 0
Complete rows for h, t and u: 168780

--- SAMPLE RECORDS ---

   station_id     date_j  heure    t      u    h   rr
0    34172005 1993-01-01      1 -4.0  101.0  0.0  0.0
1    34172005 1993-01-01      2 -3.4  101.0  0.0  0.0
2    34172005 1993-01-01      3 -4.2  101.0  0.0  0.0
3    34172005 1993-01-01      4 -5.0  101.0  0.0  0.0
4    34172005 1993-01-01      5 -4.8  100.0  0.0  0.0
5    34172005 1993-01-01      6 -5.0  100.0  0.0  0.0
6    34172005 1993-01-01      7 -5.3  100.0  0.0  0.0
7    34172005 1993-01-01      8 -4.6  100.0  0.0  0.0
8    34172005 1993-01-01      9 -1.9  101.0  0.0  0.0
9    34172005 1993-01-01     10  2.0   95.0  0.9  0.0

--- RECORDS WITH RH > 100 ---

        date_j  heure    t      u    h
0   1993-01-01      1 -4.0  101.0  0.0
1   1993-01-01      2 -3.4  101.0  0.0
2   1993-01-01      3 -4.2  101.0  0.0
3   1993-01-01      4 -5.0  101.0  0.0
8   1993-01-01      9 -1.9  101.0  0.0
165 1993-01-07     22  1.7  101.0  1.0
166 1993-01-07     23  1.6  101.0  1.0
167 1993-01-07     24  1.6  101.0  1.0
168 1993-01-08      1  4.1  102.0  1.0
175 1993-01-08      8  3.2  101.0  1.0

In [7]:

import numpy as np
import pandas as pd

# Make a separate copy; preserve the original data
q = df.copy()

# Ensure correct data types
q['date_j'] = pd.to_datetime(q['date_j'], errors='coerce')

for col in ['h', 't', 'u', 'rr', 'rg', 'par_h', 'vt', 'vx']:
    if col in q.columns:
        q[col] = pd.to_numeric(q[col], errors='coerce')

# Create a cleaned RH feature.
# RH outside its physical range is treated as invalid.
q['u_clean'] = q['u'].where(q['u'].between(0, 100))

q['year'] = q['date_j'].dt.year
q['month'] = q['date_j'].dt.month

# A complete target/input row
q['complete_row'] = q[['h', 't', 'u_clean']].notna().all(axis=1)

# True when the measured wetness duration is greater than zero
q['wet_event'] = q['h'].gt(0).astype(int)

# 1. Overall target distribution
h_valid = q['h'].dropna()

print("VALID LWD RECORDS:", len(h_valid))
print("Zero-duration records:", int((h_valid == 0).sum()))
print("Wet records (h > 0):", int((h_valid > 0).sum()))
print("Wet-record percentage:", round((h_valid > 0).mean() * 100, 2))
print("Complete h, t, RH rows:", int(q['complete_row'].sum()))

print("\nLWD duration distribution:")
print(h_valid.value_counts().sort_index().to_string())

# 2. Year-wise availability
yearly = q.groupby('year').agg(
    total_records=('h', 'size'),
    lwd_available=('h', 'count'),
    complete_rows=('complete_row', 'sum'),
    positive_lwd=('wet_event', 'sum')
)

yearly['lwd_coverage_pct'] = (
    yearly['lwd_available'] / yearly['total_records'] * 100
).round(2)

yearly['wet_pct_of_available_lwd'] = (
    yearly['positive_lwd'] / yearly['lwd_available'].replace(0, np.nan) * 100
).round(2)

print("\n--- YEAR-WISE COVERAGE ---")
display(yearly)

# 3. Month-by-year LWD availability
q['lwd_available_flag'] = q['h'].notna().astype(int)

monthly_coverage = (
    q.pivot_table(
        index='year',
        columns='month',
        values='lwd_available_flag',
        aggfunc='mean'
    ) * 100
).round(1)

monthly_coverage.columns = [
    f'Month_{int(m):02d}' for m in monthly_coverage.columns
]

print("\n--- MONTHLY COVERAGE (% available LWD) ---")
display(monthly_coverage)

# 4. Which inputs are available for future modeling?
candidate_inputs = [
    c for c in ['t', 'u_clean', 'rr', 'rg', 'par_h', 'vt', 'vx']
    if c in q.columns
]

print("\n--- INPUT MISSINGNESS ---")
display(pd.DataFrame({
    'missing_count': q[candidate_inputs].isna().sum(),
    'missing_pct': (q[candidate_inputs].isna().mean() * 100).round(2)
}))

VALID LWD RECORDS: 169108
Zero-duration records: 119428
Wet records (h > 0): 49680
Wet-record percentage: 29.38
Complete h, t, RH rows: 167906

LWD duration distribution:
h
0.0    119428
0.1      1867
0.2      1639
0.3      1493
0.4      1449
0.5      1352
0.6      1366
0.7      1437
0.8      1447
0.9      1476
1.0     36154

--- YEAR-WISE COVERAGE ---

,total_records,lwd_available,complete_rows,positive_lwd,lwd_coverage_pct,wet_pct_of_available_lwd
year,,,,,,
1993,8760,8748,7874,3908,99.86,44.67
1994,8760,8760,8760,4932,100.00,56.30
1995,8760,6552,6552,1351,74.79,20.62
1996,8784,0,0,0,0.00,NaN
1997,8760,0,0,0,0.00,NaN
1998,8760,0,0,0,0.00,NaN
1999,8760,0,0,0,0.00,NaN
2000,8784,72,72,0,0.82,0.00
2001,8760,0,0,0,0.00,NaN
2002,8760,0,0,0,0.00,NaN
2003,8760,24,24,0,0.27,0.00
2004,8784,0,0,0,0.00,NaN
2005,8760,0,0,0,0.00,NaN
2006,8760,24,24,0,0.27,0.00
2007,8760,240,240,8,2.74,3.33
2008,8784,72,72,0,0.82,0.00
2009,8760,4416,4415,1088,50.41,24.64
2010,8760,8760,8760,2629,100.00,30.01
2011,8760,8760,8760,2664,100.00,30.41
2012,8784,8784,8626,1817,100.00,20.69
2013,8760,8758,8758,2009,99.98,22.94
2014,8760,8757,8589,2244,99.97,25.63
2015,8760,8759,8759,2426,99.99,27.70
2016,8784,8756,8756,2155,99.68,24.61
2017,8760,8760,8760,1760,100.00,20.09
2018,8760,8760,8759,1582,100.00,18.06
2019,8760,8760,8760,2614,100.00,29.84
2020,8784,8783,8783,2846,99.99,32.40
2021,8760,8740,8740,2414,99.77,27.62
2022,8760,8760,8760,2562,100.00,29.25
2023,8760,8760,8760,2472,100.00,28.22
2024,8784,8784,8784,2775,100.00,31.59
2025,8760,8759,8759,3424,99.99,39.09

--- MONTHLY COVERAGE (% available LWD) ---

,Month_01,Month_02,Month_03,Month_04,Month_05,Month_06,Month_07,Month_08,Month_09,Month_10,Month_11,Month_12
year,,,,,,,,,,,,
1993,100.0,100.0,100.0,100.0,100.0,100.0,98.4,100.0,100.0,100.0,100.0,100.0
1994,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1995,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,0.0,0.0,0.0
1996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2000,9.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003,0.0,0.0,0.0,0.0,0.0,0.0,3.2,0.0,0.0,0.0,0.0,0.0
2004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2006,0.0,0.0,0.0,0.0,0.0,3.3,0.0,0.0,0.0,0.0,0.0,0.0
2007,0.0,0.0,0.0,0.0,0.0,0.0,3.2,25.8,0.0,3.2,0.0,0.0
2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.3,0.0,0.0,6.5
2009,0.0,0.0,0.0,0.0,0.0,0.0,100.0,100.0,100.0,100.0,100.0,100.0
2010,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2011,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2012,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2013,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,99.7,100.0,100.0
2014,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,99.6,100.0,100.0
2015,100.0,100.0,100.0,99.9,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2016,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,99.7,96.4,100.0
2017,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2018,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2019,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2020,100.0,100.0,100.0,100.0,100.0,100.0,99.9,100.0,100.0,100.0,100.0,100.0
2021,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,97.2,100.0,100.0,100.0
2022,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2023,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2024,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2025,100.0,100.0,100.0,100.0,100.0,99.9,100.0,100.0,100.0,100.0,100.0,100.0

--- INPUT MISSINGNESS ---

         missing_count  missing_pct
t                  291         0.10
u_clean           1159         0.40
rr                1401         0.48
rg                 137         0.05
par_h           144768        50.05
vt                 163         0.06
vx              144655        50.01

In [8]:

from pathlib import Path
from collections import defaultdict
import pandas as pd
import numpy as np

BASE_DIR = Path('/content/dataset_inspection')

hourly_files = sorted(
    BASE_DIR.glob('Station_Agroclim_INRAE_*_hourly_*.csv')
)

print("Hourly station files found:", len(hourly_files))

results = []

for file_path in hourly_files:
    # Read only the necessary columns
    cols = ['date_j', 'h', 't', 'u']

    annual = defaultdict(
        lambda: {
            'rows': 0,
            'lwd_valid': 0,
            'complete': 0
        }
    )

    first_date = None
    last_date = None
    total_rows = 0

    try:
        for chunk in pd.read_csv(
            file_path,
            usecols=cols,
            chunksize=50000,
            low_memory=False
        ):
            dates = pd.to_datetime(
                chunk['date_j'], errors='coerce'
            )

            chunk['h'] = pd.to_numeric(
                chunk['h'], errors='coerce'
            )
            chunk['t'] = pd.to_numeric(
                chunk['t'], errors='coerce'
            )
            chunk['u'] = pd.to_numeric(
                chunk['u'], errors='coerce'
            )

            valid_dates = dates.dropna()

            if not valid_dates.empty:
                dmin, dmax = valid_dates.min(), valid_dates.max()
                first_date = dmin if first_date is None else min(first_date, dmin)
                last_date = dmax if last_date is None else max(last_date, dmax)

            total_rows += len(chunk)

            years = dates.dt.year

            valid_lwd = chunk['h'].notna()
            complete = (
                valid_lwd
                & chunk['t'].notna()
                & chunk['u'].between(0, 100)
            )

            temp = pd.DataFrame({
                'year': years,
                'lwd_valid': valid_lwd.astype(int),
                'complete': complete.astype(int)
            })

            temp = temp[ temp['year'].between(2010, 2025) ]

            for year, group in temp.groupby('year'):
                annual[int(year)]['rows'] += len(group)
                annual[int(year)]['lwd_valid'] += group['lwd_valid'].sum()
                annual[int(year)]['complete'] += group['complete'].sum()

        # Summarize only 2010–2025
        period = {
            key: sum(annual[y][key] for y in range(2010, 2026))
            for key in ['rows', 'lwd_valid', 'complete']
        }

        observed_years = [
            y for y in range(2010, 2026)
            if annual[y]['rows'] > 0
        ]

        good_years = [
            y for y in observed_years
            if annual[y]['lwd_valid'] / annual[y]['rows'] >= 0.95
        ]

        results.append({
            'file': file_path.name,
            'first_date': first_date,
            'last_date': last_date,
            'rows_2010_2025': period['rows'],
            'lwd_coverage_pct': (
                round(100 * period['lwd_valid'] / period['rows'], 2)
                if period['rows'] else np.nan
            ),
            'complete_rows': period['complete'],
            'years_with_data': len(observed_years),
            'years_with_95pct_lwd': len(good_years)
        })

    except Exception as e:
        print("Could not process:", file_path.name, repr(e))

station_summary = pd.DataFrame(results)

station_summary = station_summary.sort_values(
    ['lwd_coverage_pct', 'complete_rows'],
    ascending=False,
    na_position='last'
)

print("\n--- STATION COMPARISON: 2010–2025 ---")
display(station_summary)

print("\n--- BEST CANDIDATES ---")
display(station_summary.head(15))

Hourly station files found: 54

--- STATION COMPARISON: 2010–2025 ---

,file,first_date,last_date,rows_2010_2025,lwd_coverage_pct,complete_rows,years_with_data,years_with_95pct_lwd
46,Station_Agroclim_INRAE_84007004_hourly_1988_20...,1993-01-01,2025-12-31,140256,100.00,140185,16,16
25,Station_Agroclim_INRAE_40272002_hourly_1993_20...,1993-01-17,2025-12-31,140256,100.00,140151,16,16
5,Station_Agroclim_INRAE_21106002_hourly_1990_20...,1993-01-01,2025-12-31,140256,100.00,140094,16,16
40,Station_Agroclim_INRAE_68028003_hourly_1999_20...,1999-01-22,2025-12-31,140256,100.00,140032,16,16
6,Station_Agroclim_INRAE_24340001_hourly_2021_20...,2021-06-01,2025-12-31,40200,100.00,40140,5,5
47,Station_Agroclim_INRAE_86139002_hourly_1988_20...,1994-07-21,2025-12-31,140256,99.99,140241,16,16
12,Station_Agroclim_INRAE_30258005_hourly_1986_20...,1994-03-30,2025-12-31,140256,99.99,140240,16,16
23,Station_Agroclim_INRAE_35240002_hourly_1983_20...,1993-03-02,2025-12-31,140256,99.99,140067,16,16
27,Station_Agroclim_INRAE_45234009_hourly_2010_20...,2010-10-18,2025-12-31,133296,99.99,133277,16,16
19,Station_Agroclim_INRAE_34154004_hourly_2012_20...,2012-01-01,2025-12-31,122736,99.99,122711,14,14
24,Station_Agroclim_INRAE_39130003_hourly_2014_20...,2014-07-31,2025-12-31,100128,99.99,100065,12,12
39,Station_Agroclim_INRAE_66002002_hourly_1991_20...,1993-01-01,2025-12-31,140256,99.98,139660,16,16
22,Station_Agroclim_INRAE_34337004_hourly_2013_20...,2013-06-01,2025-12-31,110328,99.98,110286,13,13
38,Station_Agroclim_INRAE_63345002_hourly_1985_20...,1993-08-05,2025-12-31,140256,99.97,140028,16,16
0,Station_Agroclim_INRAE_11170004_hourly_1989_20...,1994-06-17,2025-12-31,140256,99.97,139952,16,16
26,Station_Agroclim_INRAE_44026001_hourly_2013_20...,2013-03-28,2025-12-31,111888,99.97,111836,13,13
9,Station_Agroclim_INRAE_29179002_hourly_1993_20...,1993-05-26,2025-12-31,140256,99.96,140191,16,16
14,Station_Agroclim_INRAE_33080002_hourly_1993_20...,1993-01-21,2025-12-31,140256,99.96,140014,16,16
20,Station_Agroclim_INRAE_34172005_hourly_1990_20...,1993-01-01,2025-12-31,140256,99.96,139873,16,16
48,Station_Agroclim_INRAE_88304005_hourly_1989_20...,1998-07-23,2025-12-31,140256,99.95,140184,16,16
11,Station_Agroclim_INRAE_30117002_hourly_1991_20...,1993-01-01,2025-12-31,140256,99.95,139888,16,16
15,Station_Agroclim_INRAE_33122004_hourly_1996_20...,1996-03-01,2025-12-31,140256,99.94,140170,16,16
45,Station_Agroclim_INRAE_80557001_hourly_1985_20...,1994-03-02,2025-12-31,140256,99.94,140169,16,16
10,Station_Agroclim_INRAE_30034004_hourly_1995_20...,1995-09-13,2025-12-31,140256,99.94,140167,16,16
21,Station_Agroclim_INRAE_34237001_hourly_1992_20...,1993-01-01,2025-12-31,140256,99.92,140148,16,16
34,Station_Agroclim_INRAE_56144001_hourly_1993_20...,1993-11-23,2025-12-31,140256,99.90,139072,16,16
28,Station_Agroclim_INRAE_46084002_hourly_1992_20...,1993-01-01,2025-12-31,140256,99.84,139978,16,16
7,Station_Agroclim_INRAE_26313003_hourly_1990_20...,1993-01-01,2025-12-31,140256,99.83,139892,16,16
41,Station_Agroclim_INRAE_68066002_hourly_1985_20...,2000-03-09,2025-12-31,140256,99.82,139850,16,16
13,Station_Agroclim_INRAE_31035002_hourly_1994_20...,1994-08-11,2025-12-31,140256,99.75,139898,16,16
44,Station_Agroclim_INRAE_78646005_hourly_2001_20...,2001-02-15,2025-12-31,140256,99.75,139895,16,16
31,Station_Agroclim_INRAE_49249001_hourly_2012_20...,2012-03-01,2025-12-31,121295,99.74,120610,14,14
35,Station_Agroclim_INRAE_61328003_hourly_2010_20...,2010-02-25,2025-12-31,138935,99.73,138540,16,16
8,Station_Agroclim_INRAE_29170002_hourly_1991_20...,1993-01-01,2025-12-31,140256,99.70,139830,16,16
18,Station_Agroclim_INRAE_34150002_hourly_1999_20...,1999-12-20,2025-12-31,140256,99.69,139810,16,16
29,Station_Agroclim_INRAE_47038002_hourly_1991_20...,1993-01-01,2025-12-31,140255,99.59,139202,16,16
2,Station_Agroclim_INRAE_13103002_hourly_1992_20...,1993-01-01,2025-12-31,140256,99.58,139660,16,15
33,Station_Agroclim_INRAE_54113002_hourly_1992_20...,1993-01-01,2025-12-31,140255,99.58,139651,16,15
17,Station_Agroclim_INRAE_33550003_hourly_1991_20...,1993-01-01,2025-12-31,140256,99.56,139638,16,16
16,Station_Agroclim_INRAE_33533002_hourly_2013_20...,2013-04-01,2025-12-31,111792,99.52,111250,13,13
49,Station_Agroclim_INRAE_91272001_hourly_2019_20...,2019-12-01,2025-12-31,53352,99.42,53042,7,7
32,Station_Agroclim_INRAE_51242002_hourly_1985_20...,1993-01-01,2025-12-31,140255,99.35,139320,16,15
30,Station_Agroclim_INRAE_49215002_hourly_1986_20...,1993-01-01,2025-12-31,140256,99.11,139007,16,15
1,Station_Agroclim_INRAE_12232002_hourly_1988_20...,1996-05-10,2025-12-31,140256,98.79,138498,16,16
36,Station_Agroclim_INRAE_63113002_hourly_2017_20...,2017-03-17,2025-12-31,77088,98.50,75862,9,8
4,Station_Agroclim_INRAE_20303002_hourly_1985_20...,1993-02-15,2025-12-31,140256,97.50,136731,16,14
37,Station_Agroclim_INRAE_63189002_hourly_1995_20...,1995-07-01,2025-12-31,140256,96.12,134314,16,13
3,Station_Agroclim_INRAE_17353002_hourly_1985_20...,1994-10-06,2025-12-31,140256,95.86,134340,16,15
52,Station_Agroclim_INRAE_97118002_hourly_1993_20...,1995-09-13,2025-12-31,140208,95.50,133720,16,14
43,Station_Agroclim_INRAE_78615002_hourly_1992_20...,1993-01-01,2025-12-31,140256,93.44,131048,16,14
53,Station_Agroclim_INRAE_97119001_hourly_1994_20...,1995-09-19,2025-12-31,140208,93.19,129891,16,12
50,Station_Agroclim_INRAE_97015001_hourly_1995_20...,1995-10-19,2025-12-31,139992,91.99,128111,16,8
51,Station_Agroclim_INRAE_97117001_hourly_1988_20...,1998-03-01,2025-12-31,140208,88.20,123180,16,9
42,Station_Agroclim_INRAE_74281004_hourly_2010_20...,2010-09-15,2025-12-31,134088,0.02,30,16,0

--- BEST CANDIDATES ---

,file,first_date,last_date,rows_2010_2025,lwd_coverage_pct,complete_rows,years_with_data,years_with_95pct_lwd
46,Station_Agroclim_INRAE_84007004_hourly_1988_20...,1993-01-01,2025-12-31,140256,100.00,140185,16,16
25,Station_Agroclim_INRAE_40272002_hourly_1993_20...,1993-01-17,2025-12-31,140256,100.00,140151,16,16
5,Station_Agroclim_INRAE_21106002_hourly_1990_20...,1993-01-01,2025-12-31,140256,100.00,140094,16,16
40,Station_Agroclim_INRAE_68028003_hourly_1999_20...,1999-01-22,2025-12-31,140256,100.00,140032,16,16
6,Station_Agroclim_INRAE_24340001_hourly_2021_20...,2021-06-01,2025-12-31,40200,100.00,40140,5,5
47,Station_Agroclim_INRAE_86139002_hourly_1988_20...,1994-07-21,2025-12-31,140256,99.99,140241,16,16
12,Station_Agroclim_INRAE_30258005_hourly_1986_20...,1994-03-30,2025-12-31,140256,99.99,140240,16,16
23,Station_Agroclim_INRAE_35240002_hourly_1983_20...,1993-03-02,2025-12-31,140256,99.99,140067,16,16
27,Station_Agroclim_INRAE_45234009_hourly_2010_20...,2010-10-18,2025-12-31,133296,99.99,133277,16,16
19,Station_Agroclim_INRAE_34154004_hourly_2012_20...,2012-01-01,2025-12-31,122736,99.99,122711,14,14
24,Station_Agroclim_INRAE_39130003_hourly_2014_20...,2014-07-31,2025-12-31,100128,99.99,100065,12,12
39,Station_Agroclim_INRAE_66002002_hourly_1991_20...,1993-01-01,2025-12-31,140256,99.98,139660,16,16
22,Station_Agroclim_INRAE_34337004_hourly_2013_20...,2013-06-01,2025-12-31,110328,99.98,110286,13,13
38,Station_Agroclim_INRAE_63345002_hourly_1985_20...,1993-08-05,2025-12-31,140256,99.97,140028,16,16
0,Station_Agroclim_INRAE_11170004_hourly_1989_20...,1994-06-17,2025-12-31,140256,99.97,139952,16,16

# **combine dataset**

In [9]:

from pathlib import Path
import pandas as pd
import numpy as np

BASE_DIR = Path('/content/dataset_inspection')

# Use results from the previous station-comparison cell
if 'station_summary' not in globals():
    raise NameError(
        "station_summary not found. Run the station-comparison cell first."
    )

# 1. Select reliable stations
candidates = station_summary[
    (station_summary['lwd_coverage_pct'] >= 99.0)
    & (station_summary['complete_rows'] >= 100000)
    & (station_summary['years_with_95pct_lwd'] >= 10)
].copy()

print("Selected stations:", len(candidates))

print("\nSelected station IDs:")
candidates['station_id'] = candidates['file'].str.extract(
    r'INRAE_(\d+)_hourly_'
)
display(
    candidates[
        ['station_id', 'lwd_coverage_pct',
         'complete_rows', 'years_with_95pct_lwd']
    ].sort_values('lwd_coverage_pct', ascending=False)
)

if candidates.empty:
    raise ValueError("No stations met the quality criteria.")

selected_names = set(candidates['file'].tolist())

# 2. Load only relevant variables from selected stations
feature_columns = [
    'station_id', 'date_j', 'heure',
    'h', 't', 'u', 'rr', 'rg', 'vt'
]

frames = []

for filename in sorted(selected_names):
    path = BASE_DIR / filename

    if not path.exists():
        print("Missing file:", filename)
        continue

    station_data = pd.read_csv(
        path,
        usecols=feature_columns,
        low_memory=False
    )

    station_data['date_j'] = pd.to_datetime(
        station_data['date_j'], errors='coerce'
    )

    # Keep the target period
    station_data = station_data[
        station_data['date_j'].dt.year.between(2010, 2025)
    ].copy()

    # Convert measurements to numeric
    for col in ['h', 't', 'u', 'rr', 'rg', 'vt', 'heure']:
        station_data[col] = pd.to_numeric(
            station_data[col], errors='coerce'
        )

    # Keep raw RH for traceability; clean feature separately
    station_data['u_clean'] = station_data['u'].where(
        station_data['u'].between(0, 100)
    )

    # Discard physically invalid LWD targets
    station_data.loc[
        ~station_data['h'].between(0, 1), 'h'
    ] = np.nan

    frames.append(station_data)

# 3. Combine records
if not frames:
    raise ValueError("No station data could be loaded.")

combined = pd.concat(frames, ignore_index=True)

# 4. Add cyclic time features
hour_index = combined['heure'] % 24
month_index = combined['date_j'].dt.month - 1

combined['hour_sin'] = np.sin(2 * np.pi * hour_index / 24)
combined['hour_cos'] = np.cos(2 * np.pi * hour_index / 24)
combined['month_sin'] = np.sin(2 * np.pi * month_index / 12)
combined['month_cos'] = np.cos(2 * np.pi * month_index / 12)

print("\n--- COMBINED DATASET ---")
print("Shape:", combined.shape)
print("Number of stations:", combined['station_id'].nunique())
print("Date range:", combined['date_j'].min(),
      "to", combined['date_j'].max())

# 5. Build the initial modelling table
model_features = [
    't', 'u_clean', 'rr', 'rg', 'vt',
    'hour_sin', 'hour_cos', 'month_sin', 'month_cos'
]

model_df = combined.dropna(
    subset=['h'] + model_features
).copy()

print("\n--- INITIAL MODELLING TABLE ---")
print("Shape:", model_df.shape)
print("Stations:", model_df['station_id'].nunique())
print("Missing values in model features/target:",
      model_df[['h'] + model_features].isna().sum().sum())

print("\n--- STATION-WISE SUMMARY ---")
station_report = model_df.groupby('station_id').agg(
    rows=('h', 'size'),
    mean_lwd=('h', 'mean'),
    wet_records=('h', lambda x: (x > 0).sum()),
    wet_percentage=('h', lambda x: (x > 0).mean() * 100)
).round(3)

display(station_report)

print("\n--- SAMPLE RECORDS ---")
display(
    model_df[
        ['station_id', 'date_j', 'heure', 't',
         'u_clean', 'rr', 'rg', 'vt', 'h']
    ].head()
)

Selected stations: 41

Selected station IDs:

   station_id  lwd_coverage_pct  complete_rows  years_with_95pct_lwd
46   84007004            100.00         140185                    16
25   40272002            100.00         140151                    16
5    21106002            100.00         140094                    16
40   68028003            100.00         140032                    16
47   86139002             99.99         140241                    16
12   30258005             99.99         140240                    16
23   35240002             99.99         140067                    16
27   45234009             99.99         133277                    16
19   34154004             99.99         122711                    14
24   39130003             99.99         100065                    12
39   66002002             99.98         139660                    16
22   34337004             99.98         110286                    13
38   63345002             99.97         140028                    16
0    11170004             99.97         139952                    16
26   44026001             99.97         111836                    13
9    29179002             99.96         140191                    16
14   33080002             99.96         140014                    16
20   34172005             99.96         139873                    16
48   88304005             99.95         140184                    16
11   30117002             99.95         139888                    16
15   33122004             99.94         140170                    16
45   80557001             99.94         140169                    16
10   30034004             99.94         140167                    16
21   34237001             99.92         140148                    16
34   56144001             99.90         139072                    16
28   46084002             99.84         139978                    16
7    26313003             99.83         139892                    16
41   68066002             99.82         139850                    16
13   31035002             99.75         139898                    16
44   78646005             99.75         139895                    16
31   49249001             99.74         120610                    14
35   61328003             99.73         138540                    16
8    29170002             99.70         139830                    16
18   34150002             99.69         139810                    16
29   47038002             99.59         139202                    16
2    13103002             99.58         139660                    15
33   54113002             99.58         139651                    15
17   33550003             99.56         139638                    16
16   33533002             99.52         111250                    13
32   51242002             99.35         139320                    15
30   49215002             99.11         139007                    15

--- COMBINED DATASET ---
Shape: (5578843, 14)
Number of stations: 41
Date range: 2010-01-01 00:00:00 to 2025-12-31 00:00:00

--- INITIAL MODELLING TABLE ---
Shape: (5551465, 14)
Stations: 41
Missing values in model features/target: 0

--- STATION-WISE SUMMARY ---

              rows  mean_lwd  wet_records  wet_percentage
station_id
11170004    139952     0.171        28453          20.331
13103002    139513     0.155        25994          18.632
21106002    138786     0.220        36735          26.469
26313003    139866     0.192        31978          22.863
29170002    138321     0.412        65321          47.224
29179002    140087     0.467        74540          53.210
30034004    140162     0.205        33208          23.693
30117002    139037     0.222        36301          26.109
30258005    140240     0.163        26994          19.248
31035002    139894     0.221        38061          27.207
33080002    138364     0.314        50683          36.630
33122004    139459     0.316        50664          36.329
33533002    111074     0.327        42004          37.816
33550003    139421     0.295        48309          34.650
34150002    139769     0.323        50692          36.268
34154004    122711     0.196        28156          22.945
34172005    139789     0.235        38265          27.373
34237001    139562     0.167        27686          19.838
34337004    109985     0.196        24904          22.643
35240002    138978     0.248        41573          29.913
39130003     99685     0.384        42991          43.127
40272002    140150     0.421        66938          47.762
44026001    111828     0.321        41770          37.352
45234009    133277     0.286        44229          33.186
46084002    139978     0.318        51610          36.870
47038002    138012     0.310        49227          35.669
49215002    139002     0.223        37669          27.100
49249001    120575     0.239        34643          28.731
51242002    139309     0.205        34493          24.760
54113002    139651     0.264        42747          30.610
56144001    138862     0.386        60972          43.908
61328003    138540     0.314        49897          36.016
63345002    140025     0.262        43554          31.104
66002002    138967     0.157        26189          18.845
68028003    138900     0.217        35747          25.736
68066002    139740     0.217        37140          26.578
78646005    139814     0.290        47557          34.014
80557001    140152     0.252        42579          30.381
84007004    140145     0.179        30026          21.425
86139002    139699     0.268        44352          31.748
88304005    140184     0.271        44585          31.805

--- SAMPLE RECORDS ---

   station_id     date_j  heure    t  u_clean   rr   rg    vt    h
0    11170004 2010-01-01      1  7.8     90.0  2.0  0.0  12.0  1.0
1    11170004 2010-01-01      2  7.6     81.0  0.5  0.0  15.0  0.7
2    11170004 2010-01-01      3  8.1     80.0  0.0  0.0  18.0  0.0
3    11170004 2010-01-01      4  8.4     72.0  0.0  0.0  22.0  0.0
4    11170004 2010-01-01      5  8.5     64.0  0.0  0.0  22.0  0.0

# **combine dataset**

In [10]:

# ============================================================
# AGROCLIM COMBINED DATASET + AUTOMATIC DESCRIPTION REPORT
# Period: 2010-2025
# No ML training and no synthetic LWD generation
# ============================================================

from google.colab import drive
from pathlib import Path
from collections import defaultdict, Counter
import pandas as pd
import numpy as np
import gzip

drive.mount('/content/drive')

# ------------------------------------------------------------
# 1. Paths and station selection
# ------------------------------------------------------------

BASE_DIR = Path('/content/dataset_inspection')

OUTPUT_DIR = (
    Path('/content/drive/MyDrive') /
    'AgroClim_Combined_2010_2025'
)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

if 'station_summary' not in globals():
    raise NameError(
        "Run the previous station-comparison cell first. "
        "The variable station_summary is required."
    )

# Same quality criteria used in the previous analysis
selected = station_summary[
    (station_summary['lwd_coverage_pct'] >= 99.0)
    & (station_summary['complete_rows'] >= 100000)
    & (station_summary['years_with_95pct_lwd'] >= 10)
].copy()

selected_files = sorted(selected['file'].tolist())

if not selected_files:
    raise ValueError("No stations matched the selection criteria.")

print("Selected station files:", len(selected_files))

# ------------------------------------------------------------
# 2. Read station metadata
# ------------------------------------------------------------

metadata_path = BASE_DIR / 'stations_inrae_en_service.csv'

if metadata_path.exists():
    meta = pd.read_csv(
        metadata_path,
        sep=None,
        engine='python',
        dtype=str,
        encoding='utf-8-sig'
    )

    meta.columns = [str(c).strip() for c in meta.columns]

    id_column = next(
        (c for c in meta.columns
         if c.strip().upper().replace('_', ' ') == 'STATION ID'),
        None
    )

    if id_column is None:
        raise ValueError("Station ID column not found in metadata.")

    meta['station_id'] = (
        meta[id_column]
        .astype('string')
        .str.strip()
        .str.replace(r'\.0$', '', regex=True)
        .str.zfill(8)
    )

    metadata_fields = {
        'city': ['City'],
        'location': ['Location'],
        'altitude_m': ['Altitude (m)'],
        'longitude': ['Longitude (°Dec)'],
        'latitude': ['Latitude (°Dec)']
    }

    station_meta = pd.DataFrame({
        'station_id': meta['station_id']
    })

    for output_col, possible_names in metadata_fields.items():
        source_col = next(
            (c for c in meta.columns
             if c.strip().lower() in
             [name.lower() for name in possible_names]),
            None
        )

        station_meta[output_col] = (
            meta[source_col] if source_col else np.nan
        )

    for col in ['altitude_m', 'longitude', 'latitude']:
        station_meta[col] = pd.to_numeric(
            station_meta[col], errors='coerce'
        )

    station_meta = station_meta.drop_duplicates(
        subset='station_id',
        keep='first'
    )

else:
    print("Station metadata unavailable; location fields will be blank.")

    station_meta = pd.DataFrame(columns=[
        'station_id', 'city', 'location',
        'altitude_m', 'longitude', 'latitude'
    ])

# ------------------------------------------------------------
# 3. Define source variables
# ------------------------------------------------------------

source_columns = [
    'station_id', 'date_j', 'heure',
    'h', 'i5', 'par_h', 'rg', 'rr',
    't', 'u', 'u8', 'u9', 'vt', 'vx'
]

numeric_columns = [
    'heure', 'h', 'i5', 'par_h', 'rg', 'rr',
    't', 'u', 'u8', 'u9', 'vt', 'vx'
]

derived_columns = [
    'city', 'location', 'altitude_m',
    'longitude', 'latitude',
    'year', 'month', 'u_clean',
    'lwd_hours', 'wet_event'
]

output_columns = source_columns + derived_columns

variable_descriptions = {
    'station_id': 'INRAE station identifier.',
    'date_j': 'Source calendar date; kept separately from the hour code.',
    'heure': 'Original hour code (1-24), preserved without time-zone conversion.',
    'h': 'Original sensor-measured hourly leaf wetness duration over the preceding hour; source unit is hours and tenths.',
    'i5': 'Source actinothermal index at 50 cm; consult the source variable dictionary for its exact definition and unit.',
    'par_h': 'Hourly photosynthetically active radiation (PAR); source unit J/cm².',
    'rg': 'Hourly global radiation; source unit J/cm².',
    'rr': 'Hourly precipitation; source unit mm.',
    't': 'Instantaneous air temperature measured under shelter, in °C.',
    'u': 'Original instantaneous relative humidity in percent; raw values are preserved.',
    'u8': 'Original humidity-duration variable U8; retain source definition when interpreting it.',
    'u9': 'Duration associated with RH >90% over the hour, according to the source dictionary.',
    'vt': 'Distance travelled during the previous hour; source unit km.',
    'vx': 'Maximum hourly wind speed; source unit m/s.',
    'city': 'Station city from the supplied station metadata, if available.',
    'location': 'Station location label from the supplied metadata, if available.',
    'altitude_m': 'Station altitude in metres, if available.',
    'longitude': 'Station longitude in decimal degrees, if available.',
    'latitude': 'Station latitude in decimal degrees, if available.',
    'year': 'Calendar year derived from date_j.',
    'month': 'Calendar month derived from date_j.',
    'u_clean': 'RH feature: raw u retained only when between 0 and 100%; otherwise missing.',
    'lwd_hours': 'Analysis target copied from h only when 0 <= h <= 1 hour; otherwise missing.',
    'wet_event': '1 when valid lwd_hours > 0, 0 when valid lwd_hours = 0; missing when LWD is unavailable.'
}

# ------------------------------------------------------------
# 4. Output paths
# ------------------------------------------------------------

dataset_path = OUTPUT_DIR / 'AgroClim_Combined_2010_2025.csv.gz'

# Remove any older output before rebuilding
if dataset_path.exists():
    dataset_path.unlink()

# ------------------------------------------------------------
# 5. Streaming statistics to avoid loading all stations
#    into RAM simultaneously
# ------------------------------------------------------------

total_rows = 0
complete_rows_total = 0

missing_counts = Counter()
lwd_distribution = Counter()

year_stats = defaultdict(lambda: {
    'rows': 0,
    'lwd_available': 0,
    'complete_rows': 0,
    'wet_records': 0,
    'sum_lwd': 0.0
})

station_stats = defaultdict(lambda: {
    'rows': 0,
    'lwd_available': 0,
    'complete_rows': 0,
    'wet_records': 0,
    'sum_lwd': 0.0
})

numeric_stats = defaultdict(lambda: {
    'count': 0,
    'sum': 0.0,
    'sum_sq': 0.0,
    'min': np.inf,
    'max': -np.inf
})

stats_columns = [
    'h', 'lwd_hours', 't', 'u', 'u_clean',
    'rr', 'rg', 'par_h', 'vt', 'vx', 'i5', 'u8', 'u9'
]

sample_parts = []
first_chunk = True

# ------------------------------------------------------------
# 6. Read and combine all selected hourly files
# ------------------------------------------------------------

for file_number, filename in enumerate(selected_files, start=1):

    file_path = BASE_DIR / filename

    if not file_path.exists():
        print("Skipping missing file:", filename)
        continue

    print(f"Processing {file_number}/{len(selected_files)}: {filename}")

    for chunk in pd.read_csv(
        file_path,
        usecols=source_columns,
        dtype={'station_id': 'string'},
        chunksize=100_000,
        low_memory=False
    ):

        # Parse and filter dates
        chunk['date_j'] = pd.to_datetime(
            chunk['date_j'], errors='coerce'
        )

        chunk = chunk[
            chunk['date_j'].dt.year.between(2010, 2025)
        ].copy()

        if chunk.empty:
            continue

        # Normalize station IDs
        chunk['station_id'] = (
            chunk['station_id']
            .astype('string')
            .str.strip()
            .str.replace(r'\.0$', '', regex=True)
            .str.zfill(8)
        )

        # Preserve original measurements as supplied
        for col in numeric_columns:
            chunk[col] = pd.to_numeric(
                chunk[col], errors='coerce'
            )

        chunk['year'] = chunk['date_j'].dt.year
        chunk['month'] = chunk['date_j'].dt.month

        # Keep raw RH (u) and create a separate cleaned feature
        chunk['u_clean'] = chunk['u'].where(
            chunk['u'].between(0, 100)
        )

        # Keep raw h and make a separate valid LWD target
        chunk['lwd_hours'] = chunk['h'].where(
            chunk['h'].between(0, 1)
        )

        # A wet event is defined only when LWD is available
        chunk['wet_event'] = np.where(
            chunk['lwd_hours'].notna(),
            (chunk['lwd_hours'] > 0).astype(float),
            np.nan
        )

        # Merge location metadata without dropping unmatched records
        chunk = chunk.merge(
            station_meta,
            on='station_id',
            how='left',
            validate='many_to_one'
        )

        # Preserve original date formatting
        chunk['date_j'] = chunk['date_j'].dt.strftime('%Y-%m-%d')

        # Explicit output column order
        chunk = chunk[output_columns]

        # Write compressed dataset incrementally
        mode = 'wt' if first_chunk else 'at'

        with gzip.open(
            dataset_path,
            mode,
            encoding='utf-8',
            newline=''
        ) as output_file:
            chunk.to_csv(
                output_file,
                index=False,
                header=first_chunk
            )

        first_chunk = False

        # Overall row and missingness statistics
        total_rows += len(chunk)
        missing_counts.update(
            chunk.isna().sum().to_dict()
        )

        complete_mask = (
            chunk['lwd_hours'].notna()
            & chunk['t'].notna()
            & chunk['u_clean'].notna()
        )

        complete_rows_total += int(complete_mask.sum())

        # LWD duration distribution
        valid_lwd = chunk['lwd_hours'].dropna()

        for value, count in (
            valid_lwd.round(1).value_counts().items()
        ):
            lwd_distribution[float(value)] += int(count)

        # Numeric variable summaries
        for col in stats_columns:
            values = pd.to_numeric(
                chunk[col], errors='coerce'
            ).to_numpy(dtype=float)

            values = values[np.isfinite(values)]

            if len(values) == 0:
                continue

            stat = numeric_stats[col]
            stat['count'] += len(values)
            stat['sum'] += float(values.sum())
            stat['sum_sq'] += float(np.square(values).sum())
            stat['min'] = min(stat['min'], float(values.min()))
            stat['max'] = max(stat['max'], float(values.max()))

        # Update year-level and station-level summaries
        for year, group in chunk.groupby('year'):
            valid = group['lwd_hours'].dropna()
            complete = (
                group['lwd_hours'].notna()
                & group['t'].notna()
                & group['u_clean'].notna()
            )

            stat = year_stats[int(year)]
            stat['rows'] += len(group)
            stat['lwd_available'] += len(valid)
            stat['complete_rows'] += int(complete.sum())
            stat['wet_records'] += int((valid > 0).sum())
            stat['sum_lwd'] += float(valid.sum())

        for station_id, group in chunk.groupby('station_id'):
            valid = group['lwd_hours'].dropna()
            complete = (
                group['lwd_hours'].notna()
                & group['t'].notna()
                & group['u_clean'].notna()
            )

            stat = station_stats[str(station_id)]
            stat['rows'] += len(group)
            stat['lwd_available'] += len(valid)
            stat['complete_rows'] += int(complete.sum())
            stat['wet_records'] += int((valid > 0).sum())
            stat['sum_lwd'] += float(valid.sum())

        # Keep a small preview only
        if sum(len(s) for s in sample_parts) < 100:
            remaining = 100 - sum(len(s) for s in sample_parts)
            sample_parts.append(chunk.head(remaining).copy())

if first_chunk or total_rows == 0:
    raise RuntimeError(
        "No rows were written. Check the selected files and date range."
    )

# ------------------------------------------------------------
# 7. Create missingness report
# ------------------------------------------------------------

missing_report = pd.DataFrame({
    'column': output_columns,
    'missing_count': [
        int(missing_counts.get(c, 0)) for c in output_columns
    ]
})

missing_report['missing_percent'] = (
    missing_report['missing_count'] / total_rows * 100
).round(3)

missing_report.to_csv(
    OUTPUT_DIR / 'missingness_report.csv',
    index=False
)

# ------------------------------------------------------------
# 8. Create annual summary
# ------------------------------------------------------------

def finish_summary(stats):
    rows = stats['rows']
    available = stats['lwd_available']

    return {
        'rows': rows,
        'lwd_available': available,
        'lwd_coverage_pct': (
            100 * available / rows if rows else np.nan
        ),
        'complete_lwd_t_rh_rows': stats['complete_rows'],
        'wet_records': stats['wet_records'],
        'wet_pct_of_available_lwd': (
            100 * stats['wet_records'] / available
            if available else np.nan
        ),
        'mean_lwd_hours': (
            stats['sum_lwd'] / available
            if available else np.nan
        )
    }

annual_rows = []

for year, stats in sorted(year_stats.items()):
    annual_rows.append({
        'year': year,
        **finish_summary(stats)
    })

annual_report = pd.DataFrame(annual_rows)

annual_report.to_csv(
    OUTPUT_DIR / 'annual_summary.csv',
    index=False
)

# ------------------------------------------------------------
# 9. Create station summary
# ------------------------------------------------------------

metadata_lookup = (
    station_meta.set_index('station_id').to_dict('index')
    if len(station_meta) else {}
)

station_rows = []

for station_id, stats in sorted(station_stats.items()):
    details = metadata_lookup.get(station_id, {})

    station_rows.append({
        'station_id': station_id,
        'city': details.get('city', np.nan),
        'location': details.get('location', np.nan),
        'altitude_m': details.get('altitude_m', np.nan),
        'longitude': details.get('longitude', np.nan),
        'latitude': details.get('latitude', np.nan),
        **finish_summary(stats)
    })

station_report = pd.DataFrame(station_rows)

station_report.to_csv(
    OUTPUT_DIR / 'station_summary.csv',
    index=False
)

# ------------------------------------------------------------
# 10. Numeric statistics
# ------------------------------------------------------------

numeric_rows = []

for col, stat in numeric_stats.items():
    n = stat['count']
    mean = stat['sum'] / n if n else np.nan

    if n > 1:
        variance = (
            stat['sum_sq'] - stat['sum'] ** 2 / n
        ) / (n - 1)

        std = np.sqrt(max(variance, 0))
    else:
        std = np.nan

    numeric_rows.append({
        'variable': col,
        'valid_count': n,
        'missing_count': total_rows - n,
        'mean': mean,
        'std': std,
        'min': stat['min'] if n else np.nan,
        'max': stat['max'] if n else np.nan
    })

numeric_report = pd.DataFrame(numeric_rows)

numeric_report.to_csv(
    OUTPUT_DIR / 'numeric_statistics.csv',
    index=False
)

# ------------------------------------------------------------
# 11. LWD distribution
# ------------------------------------------------------------

lwd_report = pd.DataFrame([
    {
        'lwd_hours': value,
        'count': count,
        'percentage_of_valid_lwd': (
            100 * count / sum(lwd_distribution.values())
        )
    }
    for value, count in sorted(lwd_distribution.items())
])

lwd_report.to_csv(
    OUTPUT_DIR / 'lwd_distribution.csv',
    index=False
)

# ------------------------------------------------------------
# 12. Variable dictionary and sample preview
# ------------------------------------------------------------

variable_report = pd.DataFrame({
    'column': output_columns,
    'description': [
        variable_descriptions.get(c, 'See source documentation.')
        for c in output_columns
    ]
})

variable_report.to_csv(
    OUTPUT_DIR / 'variable_dictionary.csv',
    index=False
)

if sample_parts:
    sample_df = pd.concat(
        sample_parts, ignore_index=True
    ).head(100)

    sample_df.to_csv(
        OUTPUT_DIR / 'sample_preview.csv',
        index=False
    )

# ------------------------------------------------------------
# 13. Write plain-text dataset description
# ------------------------------------------------------------

valid_lwd_total = sum(lwd_distribution.values())
wet_total = sum(
    count for value, count in lwd_distribution.items()
    if value > 0
)

description = f"""
AGROCLIM COMBINED HOURLY DATASET: 2010-2025
============================================================

SOURCE
INRAE AgroClim station files supplied by the user.
The combined dataset includes selected hourly records from the
original source CSV files.

SELECTION CRITERIA
Stations were selected using the previously calculated station
summary:
- LWD coverage >= 99%
- At least 100,000 complete records
- At least 10 years with >= 95% LWD coverage
  during the 2010-2025 assessment period

DATASET SIZE
Total records: {total_rows:,}
Stations represented: {len(station_stats)}
Period: 2010-01-01 through 2025-12-31
Rows with valid LWD: {valid_lwd_total:,}
Valid LWD coverage: {100 * valid_lwd_total / total_rows:.2f}%
Rows complete for valid LWD, temperature and cleaned RH:
{complete_rows_total:,}

LWD DISTRIBUTION
Records with LWD > 0: {wet_total:,}
Wet records as percentage of valid LWD:
{100 * wet_total / valid_lwd_total if valid_lwd_total else np.nan:.2f}%
Mean LWD among valid records:
{numeric_report.loc[numeric_report['variable'] == 'lwd_hours', 'mean'].iloc[0]:.4f} hours

IMPORTANT COLUMN DEFINITIONS
h:
Original source column for sensor-measured hourly leaf wetness duration
over the preceding hour. The source defines the unit as hours and tenths.

lwd_hours:
A separate analysis column copied from h only when its value falls
between 0 and 1 hour. It is not synthetic or model-generated.

t:
Air temperature measured under shelter, degrees Celsius.

u:
Original relative humidity. Raw values are preserved, even if they
fall outside the physical 0-100% range.

u_clean:
A separate RH feature. Values outside 0-100% are represented as missing;
the raw u column is retained for traceability.

rr:
Hourly precipitation in millimetres.

rg:
Hourly global radiation in J/cm².

par_h:
Hourly photosynthetically active radiation in J/cm².

vt:
Distance travelled during the previous hour, in kilometres.

vx:
Maximum hourly wind speed, in metres per second.

heure:
Original hour code 1-24 is retained. No time-zone conversion or
assumption about timestamp alignment was applied.

DATA PRESERVATION AND CLEANING
- Raw source measurements are preserved.
- Missing measurements are not imputed.
- Invalid RH values are not silently clipped to 100.
- The lwd_hours column is a validated copy of h, not a new estimate.
- The source date and hour columns are retained.
- Station location fields are added where metadata is available.

POTENTIAL RESEARCH USE
1. Train and evaluate candidate LWD estimators using measured LWD as target.
2. Compare literature-based methods with sensor-trained ML methods.
3. Evaluate temporal generalization on later years.
4. Evaluate station-level generalization using held-out stations.
5. Examine how weather variables relate to measured leaf wetness.

LIMITATIONS FOR THE USER'S POTATO LATE BLIGHT STUDY
- This dataset contains weather and sensor-measured LWD, not potato disease images.
- It does not provide potato late blight labels, severity masks or image coordinates.
- It does not automatically pair any image with a matching weather station record.
- Stations are located in the AgroClim network, not necessarily in the user's
  potato-growing field or local climate.
- Estimated LWD transferred to another region must be validated; it is not
  equivalent to a local sensor measurement.
- The variables h and t/u have different measurement timing conventions.
  Check temporal alignment before final modelling.

OUTPUT FILES
AgroClim_Combined_2010_2025.csv.gz
dataset_description.txt
variable_dictionary.csv
missingness_report.csv
numeric_statistics.csv
annual_summary.csv
station_summary.csv
lwd_distribution.csv
sample_preview.csv
"""

description_path = OUTPUT_DIR / 'dataset_description.txt'
description_path.write_text(
    description.strip() + '\n',
    encoding='utf-8'
)

# Save a copy of the selection used for reproducibility
selected.to_csv(
    OUTPUT_DIR / 'selected_station_criteria.csv',
    index=False
)

# ------------------------------------------------------------
# 14. Display the key findings
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("COMBINED DATASET CREATED")
print("=" * 70)

print("Dataset:", dataset_path)
print("Compressed size (MB):", round(dataset_path.stat().st_size / 1e6, 2))
print("Description:", description_path)
print("Output folder:", OUTPUT_DIR)

print("\n--- DATASET DESCRIPTION ---")
print(description)

print("\n--- ANNUAL SUMMARY ---")
display(annual_report.round(3))

print("\n--- STATION SUMMARY ---")
display(
    station_report.sort_values(
        'lwd_coverage_pct', ascending=False
    ).head(15).round(3)
)

print("\n--- MISSINGNESS REPORT ---")
display(
    missing_report.sort_values(
        'missing_percent', ascending=False
    ).head(20)
)

print("\n--- NUMERIC STATISTICS ---")
display(numeric_report.round(3))

print("\n--- SAMPLE RECORDS ---")
display(sample_df.head(10))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Selected station files: 41
Processing 1/41: Station_Agroclim_INRAE_11170004_hourly_1989_2025.csv
Processing 2/41: Station_Agroclim_INRAE_13103002_hourly_1992_2025.csv
Processing 3/41: Station_Agroclim_INRAE_21106002_hourly_1990_2025.csv
Processing 4/41: Station_Agroclim_INRAE_26313003_hourly_1990_2025.csv
Processing 5/41: Station_Agroclim_INRAE_29170002_hourly_1991_2025.csv
Processing 6/41: Station_Agroclim_INRAE_29179002_hourly_1993_2025.csv
Processing 7/41: Station_Agroclim_INRAE_30034004_hourly_1995_2025.csv
Processing 8/41: Station_Agroclim_INRAE_30117002_hourly_1991_2025.csv
Processing 9/41: Station_Agroclim_INRAE_30258005_hourly_1986_2025.csv
Processing 10/41: Station_Agroclim_INRAE_31035002_hourly_1994_2025.csv
Processing 11/41: Station_Agroclim_INRAE_33080002_hourly_1993_2025.csv
Processing 12/41: Station_Agroclim_INRAE_33122004_hourly_1996_2025.csv
Processing 13/41: Station_Agroclim_INRAE_33533002_hourly_2013_2025.csv
Processing 14/41: Station_Agroclim_INRAE_33550003_hourly_1991_2025.csv
Processing 15/41: Station_Agroclim_INRAE_34150002_hourly_1999_2025.csv
Processing 16/41: Station_Agroclim_INRAE_34154004_hourly_2012_2025.csv
Processing 17/41: Station_Agroclim_INRAE_34172005_hourly_1990_2025.csv
Processing 18/41: Station_Agroclim_INRAE_34237001_hourly_1992_2025.csv
Processing 19/41: Station_Agroclim_INRAE_34337004_hourly_2013_2025.csv
Processing 20/41: Station_Agroclim_INRAE_35240002_hourly_1983_2025.csv
Processing 21/41: Station_Agroclim_INRAE_39130003_hourly_2014_2025.csv
Processing 22/41: Station_Agroclim_INRAE_40272002_hourly_1993_2025.csv
Processing 23/41: Station_Agroclim_INRAE_44026001_hourly_2013_2025.csv
Processing 24/41: Station_Agroclim_INRAE_45234009_hourly_2010_2025.csv
Processing 25/41: Station_Agroclim_INRAE_46084002_hourly_1992_2025.csv
Processing 26/41: Station_Agroclim_INRAE_47038002_hourly_1991_2025.csv
Processing 27/41: Station_Agroclim_INRAE_49215002_hourly_1986_2025.csv
Processing 28/41: Station_Agroclim_INRAE_49249001_hourly_2012_2025.csv
Processing 29/41: Station_Agroclim_INRAE_51242002_hourly_1985_2025.csv
Processing 30/41: Station_Agroclim_INRAE_54113002_hourly_1992_2025.csv
Processing 31/41: Station_Agroclim_INRAE_56144001_hourly_1993_2025.csv
Processing 32/41: Station_Agroclim_INRAE_61328003_hourly_2010_2025.csv
Processing 33/41: Station_Agroclim_INRAE_63345002_hourly_1985_2025.csv
Processing 34/41: Station_Agroclim_INRAE_66002002_hourly_1991_2025.csv
Processing 35/41: Station_Agroclim_INRAE_68028003_hourly_1999_2025.csv
Processing 36/41: Station_Agroclim_INRAE_68066002_hourly_1985_2025.csv
Processing 37/41: Station_Agroclim_INRAE_78646005_hourly_2001_2025.csv
Processing 38/41: Station_Agroclim_INRAE_80557001_hourly_1985_2025.csv
Processing 39/41: Station_Agroclim_INRAE_84007004_hourly_1988_2025.csv
Processing 40/41: Station_Agroclim_INRAE_86139002_hourly_1988_2025.csv
Processing 41/41: Station_Agroclim_INRAE_88304005_hourly_1989_2025.csv

======================================================================
COMBINED DATASET CREATED
======================================================================
Dataset: /content/drive/MyDrive/AgroClim_Combined_2010_2025/AgroClim_Combined_2010_2025.csv.gz
Compressed size (MB): 79.55
Description: /content/drive/MyDrive/AgroClim_Combined_2010_2025/dataset_description.txt
Output folder: /content/drive/MyDrive/AgroClim_Combined_2010_2025

--- DATASET DESCRIPTION ---

AGROCLIM COMBINED HOURLY DATASET: 2010-2025
============================================================

SOURCE
INRAE AgroClim station files supplied by the user.
The combined dataset includes selected hourly records from the
original source CSV files.

SELECTION CRITERIA
Stations were selected using the previously calculated station
summary:
- LWD coverage >= 99%
- At least 100,000 complete records
- At least 10 years with >= 95% LWD coverage
  during the 2010-2025 assessment period

DATASET SIZE
Total records: 5,578,843
Stations represented: 41
Period: 2010-01-01 through 2025-12-31
Rows with valid LWD: 5,569,694
Valid LWD coverage: 99.84%
Rows complete for valid LWD, temperature and cleaned RH:
5,564,730

LWD DISTRIBUTION
Records with LWD > 0: 1,715,575
Wet records as percentage of valid LWD:
30.80%
Mean LWD among valid records:
0.2633 hours

IMPORTANT COLUMN DEFINITIONS
h:
Original source column for sensor-measured hourly leaf wetness duration
over the preceding hour. The source defines the unit as hours and tenths.

lwd_hours:
A separate analysis column copied from h only when its value falls
between 0 and 1 hour. It is not synthetic or model-generated.

t:
Air temperature measured under shelter, degrees Celsius.

u:
Original relative humidity. Raw values are preserved, even if they
fall outside the physical 0-100% range.

u_clean:
A separate RH feature. Values outside 0-100% are represented as missing;
the raw u column is retained for traceability.

rr:
Hourly precipitation in millimetres.

rg:
Hourly global radiation in J/cm².

par_h:
Hourly photosynthetically active radiation in J/cm².

vt:
Distance travelled during the previous hour, in kilometres.

vx:
Maximum hourly wind speed, in metres per second.

heure:
Original hour code 1-24 is retained. No time-zone conversion or
assumption about timestamp alignment was applied.

DATA PRESERVATION AND CLEANING
- Raw source measurements are preserved.
- Missing measurements are not imputed.
- Invalid RH values are not silently clipped to 100.
- The lwd_hours column is a validated copy of h, not a new estimate.
- The source date and hour columns are retained.
- Station location fields are added where metadata is available.

POTENTIAL RESEARCH USE
1. Train and evaluate candidate LWD estimators using measured LWD as target.
2. Compare literature-based methods with sensor-trained ML methods.
3. Evaluate temporal generalization on later years.
4. Evaluate station-level generalization using held-out stations.
5. Examine how weather variables relate to measured leaf wetness.

LIMITATIONS FOR THE USER'S POTATO LATE BLIGHT STUDY
- This dataset contains weather and sensor-measured LWD, not potato disease images.
- It does not provide potato late blight labels, severity masks or image coordinates.
- It does not automatically pair any image with a matching weather station record.
- Stations are located in the AgroClim network, not necessarily in the user's
  potato-growing field or local climate.
- Estimated LWD transferred to another region must be validated; it is not
  equivalent to a local sensor measurement.
- The variables h and t/u have different measurement timing conventions.
  Check temporal alignment before final modelling.

OUTPUT FILES
AgroClim_Combined_2010_2025.csv.gz
dataset_description.txt
variable_dictionary.csv
missingness_report.csv
numeric_statistics.csv
annual_summary.csv
station_summary.csv
lwd_distribution.csv
sample_preview.csv


--- ANNUAL SUMMARY ---

,year,rows,lwd_available,lwd_coverage_pct,complete_lwd_t_rh_rows,wet_records,wet_pct_of_available_lwd,mean_lwd_hours
0,2010,298320,298103,99.927,298076,83382,27.971,0.232
1,2011,306600,306360,99.922,306175,83080,27.118,0.223
2,2012,323568,323343,99.930,322993,81704,25.269,0.203
3,2013,342547,341891,99.808,341845,87038,25.458,0.204
4,2014,354096,353814,99.920,352342,89612,25.327,0.201
5,2015,359160,358940,99.939,358823,90879,25.319,0.208
6,2016,360144,359388,99.790,359073,97330,27.082,0.224
7,2017,359160,358507,99.818,358339,92744,25.870,0.218
8,2018,359160,358582,99.839,358122,122374,34.127,0.301
9,2019,359160,359152,99.998,359152,131661,36.659,0.323
10,2020,360144,358957,99.670,358810,129484,36.072,0.318
11,2021,359160,357895,99.648,357353,125943,35.190,0.311
12,2022,359160,358807,99.902,358078,117009,32.611,0.285
13,2023,359160,358665,99.862,358570,123555,34.449,0.302
14,2024,360144,359436,99.803,359194,138806,38.618,0.342
15,2025,359160,357854,99.636,357785,120974,33.805,0.298

--- STATION SUMMARY ---

,station_id,city,location,altitude_m,longitude,latitude,rows,lwd_available,lwd_coverage_pct,complete_lwd_t_rh_rows,wet_records,wet_pct_of_available_lwd,mean_lwd_hours
2,21106002,BRETENIÈRE,ÉPOISSES,211,5.102,47.239,140256,140256,100.000,140094,37197,26.521,0.221
38,84007004,AVIGNON,SAINT-PAUL,24,4.877,43.916,140256,140254,99.999,140185,30036,21.415,0.179
21,40272002,SAINT-MARTIN-DE-HINX,LE MAIS,65,-1.299,43.571,140256,140254,99.999,140151,66982,47.758,0.421
34,68028003,BERGHEIM,BURLENBERG,309,7.347,48.216,140256,140251,99.996,140032,36024,25.685,0.217
8,30258005,SAINT-GILLES,MAS D'ASPORT,72,4.410,43.718,140256,140242,99.990,140240,26994,19.248,0.163
39,86139002,LUSIGNAN,LES VERRINES,150,0.119,46.418,140256,140241,99.989,140241,44496,31.728,0.268
23,45234009,ORLÉANS,INRA,103,1.909,47.827,133296,133280,99.988,133277,44231,33.187,0.286
20,39130003,CHAUX-DES-PRÉS,INRA,852,5.865,46.509,100128,100115,99.987,100065,43197,43.147,0.384
15,34154004,MAUGUIO,DOMAINE DE MELGUEIL,7,3.979,43.613,122736,122720,99.987,122711,28156,22.943,0.196
19,35240002,LE RHEU,LE GRAND VERRIÈRE,34,-1.781,48.113,140256,140237,99.986,140067,41866,29.854,0.247
18,34337004,VILLENEUVE-LÈS-MAGUELONE,ARGELE,20,3.854,43.538,110328,110308,99.982,110286,25014,22.677,0.197
33,66002002,ALÉNYA,MAS BLANC,10,2.970,42.638,140256,140223,99.976,139660,26534,18.923,0.158
32,63345002,SAINT-GÈNES-CHAMPANELLE,THEIX,890,3.019,45.723,140256,140219,99.974,140028,43634,31.118,0.262
22,44026001,CARQUEFOU,CTIFL,20,-1.461,47.287,111888,111856,99.971,111836,41770,37.343,0.321
0,11170004,GRUISSAN,PECH-ROUGE,40,3.136,43.143,140256,140215,99.971,139952,28487,20.317,0.171

--- MISSINGNESS REPORT ---

        column  missing_count  missing_percent
5        par_h          72570            1.301
7           rr          16539            0.296
4           i5          10679            0.191
9            u           9392            0.168
21     u_clean           9392            0.168
22   lwd_hours           9149            0.164
23   wet_event           9149            0.164
3            h           9147            0.164
10          u8           8633            0.155
13          vx           8509            0.153
12          vt           8491            0.152
8            t           7409            0.133
6           rg           5992            0.107
11          u9           5917            0.106
2        heure              0            0.000
0   station_id              0            0.000
1       date_j              0            0.000
14        city              0            0.000
15    location              0            0.000
16  altitude_m              0            0.000

--- NUMERIC STATISTICS ---

     variable  valid_count  missing_count    mean     std   min    max
0           h      5569696           9147   0.263   0.423   0.0    1.5
1   lwd_hours      5569694           9149   0.263   0.423   0.0    1.0
2           t      5571434           7409  13.183   7.600 -35.9   44.7
3           u      5569451           9392  76.271  19.515   0.0  100.0
4     u_clean      5569451           9392  76.271  19.515   0.0  100.0
5          rr      5562304          16539   0.087   0.596   0.0   81.0
6          rg      5572851           5992  56.538  87.085   0.0  490.0
7       par_h      5506273          72570  26.038  40.596   0.0  462.0
8          vt      5570352           8491   6.663   5.369   0.0   64.0
9          vx      5570334           8509   4.294   2.986   0.0   50.0
10         i5      5568164          10679  13.719   8.725 -26.3   50.5
11         u8      5570210           8633   0.185   0.348   0.0    1.0
12         u9      5572926           5917   0.330   0.454   0.0    1.0

--- SAMPLE RECORDS ---

,station_id,date_j,heure,h,i5,par_h,rg,rr,t,u,...,city,location,altitude_m,longitude,latitude,year,month,u_clean,lwd_hours,wet_event
0,11170004,2010-01-01,1,1.0,7.0,0.0,0,2.0,7.8,90.0,...,GRUISSAN,PECH-ROUGE,40,3.13551,43.14322,2010,1,90.0,1.0,1.0
1,11170004,2010-01-01,2,0.7,6.6,0.0,0,0.5,7.6,81.0,...,GRUISSAN,PECH-ROUGE,40,3.13551,43.14322,2010,1,81.0,0.7,1.0
2,11170004,2010-01-01,3,0.0,7.9,0.0,0,0.0,8.1,80.0,...,GRUISSAN,PECH-ROUGE,40,3.13551,43.14322,2010,1,80.0,0.0,0.0
3,11170004,2010-01-01,4,0.0,8.1,0.0,0,0.0,8.4,72.0,...,GRUISSAN,PECH-ROUGE,40,3.13551,43.14322,2010,1,72.0,0.0,0.0
4,11170004,2010-01-01,5,0.0,8.1,0.0,0,0.0,8.5,64.0,...,GRUISSAN,PECH-ROUGE,40,3.13551,43.14322,2010,1,64.0,0.0,0.0
5,11170004,2010-01-01,6,0.0,8.3,0.0,0,0.0,8.6,60.0,...,GRUISSAN,PECH-ROUGE,40,3.13551,43.14322,2010,1,60.0,0.0,0.0
6,11170004,2010-01-01,7,0.0,8.2,0.0,0,0.0,8.5,57.0,...,GRUISSAN,PECH-ROUGE,40,3.13551,43.14322,2010,1,57.0,0.0,0.0
7,11170004,2010-01-01,8,0.0,8.6,0.0,2,0.0,8.8,55.0,...,GRUISSAN,PECH-ROUGE,40,3.13551,43.14322,2010,1,55.0,0.0,0.0
8,11170004,2010-01-01,9,0.0,9.0,12.0,22,0.0,8.8,57.0,...,GRUISSAN,PECH-ROUGE,40,3.13551,43.14322,2010,1,57.0,0.0,0.0
9,11170004,2010-01-01,10,0.0,9.0,22.0,44,0.0,8.6,63.0,...,GRUISSAN,PECH-ROUGE,40,3.13551,43.14322,2010,1,63.0,0.0,0.0